/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Campaign } from './campaign';

/**
 * Campaign details with type-specific parameters
 * @export
 * @interface CampaignDetailsResponse
 */
export interface CampaignDetailsResponse {
    /**
     * 
     * @type {Campaign}
     * @memberof CampaignDetailsResponse
     */
    'campaign'?: Campaign;
    /**
     * Type-specific campaign parameters
     * @type {object}
     * @memberof CampaignDetailsResponse
     */
    'params'?: object;
}

