/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { KeywordRuleRequest } from './keyword-rule-request';

/**
 * Request to create a new keyword set
 * @export
 * @interface CreateKeywordSetRequest
 */
export interface CreateKeywordSetRequest {
    /**
     * Keyword set description
     * @type {string}
     * @memberof CreateKeywordSetRequest
     */
    'description'?: string;
    /**
     * Whether the keyword set is enabled
     * @type {boolean}
     * @memberof CreateKeywordSetRequest
     */
    'isEnabled'?: boolean;
    /**
     * Keyword set name
     * @type {string}
     * @memberof CreateKeywordSetRequest
     */
    'name': string;
    /**
     * List of keyword rules to include in the set
     * @type {Array<KeywordRuleRequest>}
     * @memberof CreateKeywordSetRequest
     */
    'rules'?: Array<KeywordRuleRequest>;
}

