/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteProxyPool200Response
 */
export interface DeleteProxyPool200Response {
    /**
     * Deletion status
     * @type {boolean}
     * @memberof DeleteProxyPool200Response
     */
    'deleted'?: boolean;
}

