/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DNS persona configuration details
 * @export
 * @interface DNSConfigDetails
 */
export interface DNSConfigDetails {
    /**
     * Concurrent queries per domain
     * @type {number}
     * @memberof DNSConfigDetails
     */
    'concurrentQueriesPerDomain'?: number;
    /**
     * Maximum concurrent goroutines
     * @type {number}
     * @memberof DNSConfigDetails
     */
    'maxConcurrentGoroutines'?: number;
    /**
     * Maximum domains per request
     * @type {number}
     * @memberof DNSConfigDetails
     */
    'maxDomainsPerRequest'?: number;
    /**
     * Maximum query delay in milliseconds
     * @type {number}
     * @memberof DNSConfigDetails
     */
    'queryDelayMaxMs'?: number;
    /**
     * Minimum query delay in milliseconds
     * @type {number}
     * @memberof DNSConfigDetails
     */
    'queryDelayMinMs'?: number;
    /**
     * Query timeout in seconds
     * @type {number}
     * @memberof DNSConfigDetails
     */
    'queryTimeoutSeconds'?: number;
    /**
     * Rate limit burst size
     * @type {number}
     * @memberof DNSConfigDetails
     */
    'rateLimitBurst'?: number;
    /**
     * Rate limit in domains per second
     * @type {number}
     * @memberof DNSConfigDetails
     */
    'rateLimitDps'?: number;
    /**
     * Resolver selection strategy
     * @type {string}
     * @memberof DNSConfigDetails
     */
    'resolverStrategy'?: DNSConfigDetailsResolverStrategyEnum;
    /**
     * DNS resolver addresses
     * @type {Array<string>}
     * @memberof DNSConfigDetails
     */
    'resolvers'?: Array<string>;
    /**
     * Whether to use system resolvers
     * @type {boolean}
     * @memberof DNSConfigDetails
     */
    'useSystemResolvers'?: boolean;
}

export const DNSConfigDetailsResolverStrategyEnum = {
    RoundRobin: 'round_robin',
    Random: 'random',
    Weighted: 'weighted',
    Priority: 'priority'
} as const;

export type DNSConfigDetailsResolverStrategyEnum = typeof DNSConfigDetailsResolverStrategyEnum[keyof typeof DNSConfigDetailsResolverStrategyEnum];


