openapi: 3.1.0
info:
  title: Test API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v2
paths:
  /health:
    get:
      summary: Health check
      operationId: health_check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
components:
  schemas:
    $ref: './test-schema.yaml'
