/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AnalyticsAlertConfig
 */
export interface AnalyticsAlertConfig {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsAlertConfig
     */
    'errorRateThreshold'?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsAlertConfig
     */
    'performanceThreshold'?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsAlertConfig
     */
    'resourceUsageThreshold'?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsAlertConfig
     */
    'stealthScoreThreshold'?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsAlertConfig
     */
    'successRateThreshold'?: number;
}

