/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AnalysisConfig
 */
export interface AnalysisConfig {
    /**
     * 
     * @type {string}
     * @memberof AnalysisConfig
     */
    'analysisType': 'basic' | 'comprehensive' | 'custom';
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalysisConfig
     */
    'customRules'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AnalysisConfig
     */
    'generateReport'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AnalysisConfig
     */
    'includeScreenshots'?: boolean;
}

/**
    * @export
    * @enum {string}
    */
// Enum AnalysisConfigAnalysisTypeEnum converted to direct string literals in interface


