/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiPageInfo } from './api-page-info';
// May contain unused imports in some cases
// @ts-ignore
import type { ApiProcessingInfo } from './api-processing-info';
// May contain unused imports in some cases
// @ts-ignore
import type { ApiRateLimitInfo } from './api-rate-limit-info';

/**
 * Optional metadata attached to API responses
 * @export
 * @interface ApiMetadata
 */
export interface ApiMetadata {
    /**
     * Additional metadata
     * @type {{ [key: string]: any; }}
     * @memberof ApiMetadata
     */
    'extra'?: { [key: string]: any; };
    /**
     * 
     * @type {ApiPageInfo}
     * @memberof ApiMetadata
     */
    'page'?: ApiPageInfo;
    /**
     * 
     * @type {ApiProcessingInfo}
     * @memberof ApiMetadata
     */
    'processing'?: ApiProcessingInfo;
    /**
     * 
     * @type {ApiRateLimitInfo}
     * @memberof ApiMetadata
     */
    'rateLimit'?: ApiRateLimitInfo;
}

