/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiLoggingConfig
 */
export interface ApiLoggingConfig {
    /**
     * 
     * @type {boolean}
     * @memberof ApiLoggingConfig
     */
    'enableFileLogging'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiLoggingConfig
     */
    'enableJSONFormat'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiLoggingConfig
     */
    'enablePerformanceLogging'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiLoggingConfig
     */
    'enableRequestLogging'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiLoggingConfig
     */
    'level'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLoggingConfig
     */
    'logDirectory'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiLoggingConfig
     */
    'maxAge'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiLoggingConfig
     */
    'maxBackups'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiLoggingConfig
     */
    'maxFileSize'?: number;
}

