/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiProxyDetailsResponse
 */
export interface ApiProxyDetailsResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiProxyDetailsResponse
     */
    'host'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiProxyDetailsResponse
     */
    'port'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiProxyDetailsResponse
     */
    'protocol'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProxyDetailsResponse
     */
    'username'?: string;
}

