/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Bulk operation metadata
 * @export
 * @interface ApiBulkOperationInfo
 */
export interface ApiBulkOperationInfo {
    /**
     * List of item IDs that failed processing
     * @type {Array<string>}
     * @memberof ApiBulkOperationInfo
     */
    'failedItems'?: Array<string>;
    /**
     * Number of items successfully processed
     * @type {number}
     * @memberof ApiBulkOperationInfo
     */
    'processedItems'?: number;
    /**
     * Total processing time in milliseconds
     * @type {number}
     * @memberof ApiBulkOperationInfo
     */
    'processingTimeMs'?: number;
    /**
     * Number of items skipped due to errors
     * @type {number}
     * @memberof ApiBulkOperationInfo
     */
    'skippedItems'?: number;
    /**
     * For database operations
     * @type {number}
     * @memberof ApiBulkOperationInfo
     */
    'totalRowsReturned'?: number;
    /**
     * Type of bulk operation (campaigns, queries, etc.)
     * @type {string}
     * @memberof ApiBulkOperationInfo
     */
    'type'?: string;
}

