/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request payload for configuring campaign phase parameters
 * @export
 * @interface ApiPhaseConfigureRequest
 */
export interface ApiPhaseConfigureRequest {
    /**
     * 
     * @type {any}
     * @memberof ApiPhaseConfigureRequest
     */
    'config': any;
    /**
     * 
     * @type {string}
     * @memberof ApiPhaseConfigureRequest
     */
    'phaseType': 'dns_validation' | 'http_keyword_validation' | 'analysis';
}

/**
    * @export
    * @enum {string}
    */
// Enum ApiPhaseConfigureRequestPhaseTypeEnum converted to direct string literals in interface


