/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiDNSValidatorConfigJSON
 */
export interface ApiDNSValidatorConfigJSON {
    /**
     * 
     * @type {number}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'concurrentQueriesPerDomain'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'maxConcurrentGoroutines'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'maxDomainsPerRequest'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'queryDelayMaxMs'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'queryDelayMinMs'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'queryTimeoutSeconds'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'rateLimitBurst'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'rateLimitDps'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'resolverStrategy'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'resolvers'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'resolversPreferredOrder'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'resolversWeighted'?: { [key: string]: number; };
    /**
     * 
     * @type {boolean}
     * @memberof ApiDNSValidatorConfigJSON
     */
    'useSystemResolvers'?: boolean;
}

