/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ErrorCode } from './error-code';
// May contain unused imports in some cases
// @ts-ignore
import type { FlexibleValue } from './flexible-value';

/**
 * 
 * @export
 * @interface ApiErrorDetailsInner
 */
export interface ApiErrorDetailsInner {
    /**
     * JSON pointer or field path
     * @type {string}
     * @memberof ApiErrorDetailsInner
     */
    'field'?: string;
    /**
     * 
     * @type {ErrorCode}
     * @memberof ApiErrorDetailsInner
     */
    'code': ErrorCode;
    /**
     * 
     * @type {string}
     * @memberof ApiErrorDetailsInner
     */
    'message': string;
    /**
     * Structured error context values constrained to primitive/array/object envelope.
     * @type {{ [key: string]: FlexibleValue; }}
     * @memberof ApiErrorDetailsInner
     */
    'context'?: { [key: string]: FlexibleValue; };
}



