/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubComFntelecomllcStudioBackendInternalModelsPhaseStatusEnum } from './github-com-fntelecomllc-studio-backend-internal-models-phase-status-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { GithubComFntelecomllcStudioBackendInternalModelsPhaseTypeEnum } from './github-com-fntelecomllc-studio-backend-internal-models-phase-type-enum';

/**
 * Campaign summary with phase-centric bulk data
 * @export
 * @interface ApiCampaignSummary
 */
export interface ApiCampaignSummary {
    /**
     * 
     * @type {string}
     * @memberof ApiCampaignSummary
     */
    'campaignId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCampaignSummary
     */
    'createdAt'?: string;
    /**
     * 
     * @type {GithubComFntelecomllcStudioBackendInternalModelsPhaseTypeEnum}
     * @memberof ApiCampaignSummary
     */
    'currentPhase'?: GithubComFntelecomllcStudioBackendInternalModelsPhaseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiCampaignSummary
     */
    'name'?: string;
    /**
     * 
     * @type {GithubComFntelecomllcStudioBackendInternalModelsPhaseStatusEnum}
     * @memberof ApiCampaignSummary
     */
    'phaseStatus'?: GithubComFntelecomllcStudioBackendInternalModelsPhaseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ApiCampaignSummary
     */
    'totalItems'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiCampaignSummary
     */
    'updatedAt'?: string;
}



