/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiDatabaseQuery } from './api-database-query';

/**
 * Request payload for executing multiple database queries in a single operation
 * @export
 * @interface ApiBulkDatabaseQueryRequest
 */
export interface ApiBulkDatabaseQueryRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiBulkDatabaseQueryRequest
     */
    'limit'?: number;
    /**
     * 
     * @type {Array<ApiDatabaseQuery>}
     * @memberof ApiBulkDatabaseQueryRequest
     */
    'queries': Array<ApiDatabaseQuery>;
    /**
     * 
     * @type {number}
     * @memberof ApiBulkDatabaseQueryRequest
     */
    'timeout'?: number;
}

