/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiDatabaseQueryResult } from './api-database-query-result';

/**
 * Response containing results from multiple database queries
 * @export
 * @interface ApiBulkDatabaseQueryResponse
 */
export interface ApiBulkDatabaseQueryResponse {
    /**
     * 
     * @type {{ [key: string]: ApiDatabaseQueryResult; }}
     * @memberof ApiBulkDatabaseQueryResponse
     */
    'results'?: { [key: string]: ApiDatabaseQueryResult; };
    /**
     * 
     * @type {number}
     * @memberof ApiBulkDatabaseQueryResponse
     */
    'totalCount'?: number;
}

