/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiProxyHealthCheckResponse } from './api-proxy-health-check-response';

/**
 * 
 * @export
 * @interface ApiBulkHealthCheckResponse
 */
export interface ApiBulkHealthCheckResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiBulkHealthCheckResponse
     */
    'failedProxies'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiBulkHealthCheckResponse
     */
    'healthyProxies'?: number;
    /**
     * 
     * @type {Array<ApiProxyHealthCheckResponse>}
     * @memberof ApiBulkHealthCheckResponse
     */
    'results'?: Array<ApiProxyHealthCheckResponse>;
    /**
     * 
     * @type {number}
     * @memberof ApiBulkHealthCheckResponse
     */
    'totalProxies'?: number;
}

