/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthAuditLog
 */
export interface AuthAuditLog {
    /**
     * 
     * @type {string}
     * @memberof AuthAuditLog
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAuditLog
     */
    'details'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAuditLog
     */
    'eventStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAuditLog
     */
    'eventType'?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthAuditLog
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthAuditLog
     */
    'ipAddress'?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthAuditLog
     */
    'riskScore'?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthAuditLog
     */
    'securityFlags'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAuditLog
     */
    'sessionFingerprint'?: string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof AuthAuditLog
     */
    'sessionId'?: UUID;
    /**
     * 
     * @type {string}
     * @memberof AuthAuditLog
     */
    'userAgent'?: string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof AuthAuditLog
     */
    'userId'?: UUID;
}

