/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthConfigPasswordPolicy } from './auth-config-password-policy';

/**
 * Authentication configuration
 * @export
 * @interface AuthConfig
 */
export interface AuthConfig {
  /**
   * Authentication provider type
   * @memberof AuthConfig
   */
  'provider': 
      'none' | 'local' | 'oauth2' | 'saml'
;
  /**
   * Whether authentication is enforced
   * @memberof AuthConfig
   */
  'enabled': 
        
          
          boolean
    ;
  /**
   * JWT issuer claim value
   * @memberof AuthConfig
   */
  'jwtIssuer'?: 
        
          
          string
    ;
  /**
   * JWT audience claim value
   * @memberof AuthConfig
   */
  'jwtAudience'?: 
        
          
          string
    ;
  /**
   * Access token time-to-live in seconds
   * @memberof AuthConfig
   */
  'accessTokenTtlSeconds': 
        
          
          number
    ;
  /**
   * Refresh token time-to-live in seconds
   * @memberof AuthConfig
   */
  'refreshTokenTtlSeconds': 
        
          
          number
    ;
  /**
   * Providers enabled system-wide
   * @memberof AuthConfig
   */
  'allowedProviders'?: 
        
          
          Array<string>
    ;
  /**
   * 
   * @memberof AuthConfig
   */
  'passwordPolicy'?: 
        
          
          AuthConfigPasswordPolicy
    ;
}


