/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthorizationDecision
 */
export interface AuthorizationDecision {
    /**
     * 
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'action'?: string;
    /**
     * 
     * @type {object}
     * @memberof AuthorizationDecision
     */
    'conditionsMet'?: object;
    /**
     * 
     * @type {object}
     * @memberof AuthorizationDecision
     */
    'context'?: object;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'decision'?: string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'decisionId'?: UUID;
    /**
     * 
     * @type {number}
     * @memberof AuthorizationDecision
     */
    'decisionTimeMs'?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'evaluatedPolicies'?: string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'id'?: UUID;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'policyVersion'?: string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'resourceId'?: UUID;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'resourceType'?: string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'securityEventId'?: UUID;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof AuthorizationDecision
     */
    'userId'?: UUID;
}

