/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CostBaselineMetrics } from './cost-baseline-metrics';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationalBaselineMetrics } from './operational-baseline-metrics';
// May contain unused imports in some cases
// @ts-ignore
import type { PerformanceBaselineMetrics } from './performance-baseline-metrics';
// May contain unused imports in some cases
// @ts-ignore
import type { QualityBaselineMetrics } from './quality-baseline-metrics';
// May contain unused imports in some cases
// @ts-ignore
import type { ResourceBaselineMetrics } from './resource-baseline-metrics';
// May contain unused imports in some cases
// @ts-ignore
import type { StealthBaselineMetrics } from './stealth-baseline-metrics';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeRangeFilter } from './time-range-filter';

/**
 * 
 * @export
 * @interface BaselineMetrics
 */
export interface BaselineMetrics {
    /**
     * 
     * @type {CostBaselineMetrics}
     * @memberof BaselineMetrics
     */
    'costMetrics'?: CostBaselineMetrics;
    /**
     * 
     * @type {OperationalBaselineMetrics}
     * @memberof BaselineMetrics
     */
    'operationalMetrics'?: OperationalBaselineMetrics;
    /**
     * 
     * @type {PerformanceBaselineMetrics}
     * @memberof BaselineMetrics
     */
    'performanceMetrics'?: PerformanceBaselineMetrics;
    /**
     * 
     * @type {QualityBaselineMetrics}
     * @memberof BaselineMetrics
     */
    'qualityMetrics'?: QualityBaselineMetrics;
    /**
     * 
     * @type {ResourceBaselineMetrics}
     * @memberof BaselineMetrics
     */
    'resourceMetrics'?: ResourceBaselineMetrics;
    /**
     * 
     * @type {StealthBaselineMetrics}
     * @memberof BaselineMetrics
     */
    'stealthMetrics'?: StealthBaselineMetrics;
    /**
     * 
     * @type {TimeRangeFilter}
     * @memberof BaselineMetrics
     */
    'timePeriod'?: TimeRangeFilter;
}

