/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BulkResourceAllocationResponseAllocation } from './bulk-resource-allocation-response-allocation';
// May contain unused imports in some cases
// @ts-ignore
import type { BulkResourceAllocationResponseEndpoints } from './bulk-resource-allocation-response-endpoints';
// May contain unused imports in some cases
// @ts-ignore
import type { BulkResourceAllocationResponseResources } from './bulk-resource-allocation-response-resources';

/**
 * 
 * @export
 * @interface BulkResourceAllocationResponse
 */
export interface BulkResourceAllocationResponse {
    /**
     * 
     * @type {string}
     * @memberof BulkResourceAllocationResponse
     */
    'allocationId': string;
    /**
     * 
     * @type {string}
     * @memberof BulkResourceAllocationResponse
     */
    'status': BulkResourceAllocationResponseStatusEnum;
    /**
     * 
     * @type {BulkResourceAllocationResponseResources}
     * @memberof BulkResourceAllocationResponse
     */
    'resources': BulkResourceAllocationResponseResources;
    /**
     * 
     * @type {BulkResourceAllocationResponseAllocation}
     * @memberof BulkResourceAllocationResponse
     */
    'allocation': BulkResourceAllocationResponseAllocation;
    /**
     * 
     * @type {BulkResourceAllocationResponseEndpoints}
     * @memberof BulkResourceAllocationResponse
     */
    'endpoints'?: BulkResourceAllocationResponseEndpoints;
}

/**
    * @export
    * @enum {string}
    */
export enum BulkResourceAllocationResponseStatusEnum {
    allocating = 'allocating',
    allocated = 'allocated',
    failed = 'failed'
}


