/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AggregatedAnalytics } from './aggregated-analytics';
// May contain unused imports in some cases
// @ts-ignore
import type { BulkMetadata } from './bulk-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { CampaignAnalytics } from './campaign-analytics';

/**
 * 
 * @export
 * @interface BulkAnalyticsResponse
 */
export interface BulkAnalyticsResponse {
    /**
     * 
     * @type {AggregatedAnalytics}
     * @memberof BulkAnalyticsResponse
     */
    'aggregatedData'?: AggregatedAnalytics;
    /**
     * 
     * @type {{ [key: string]: CampaignAnalytics; }}
     * @memberof BulkAnalyticsResponse
     */
    'campaignMetrics'?: { [key: string]: CampaignAnalytics; };
    /**
     * 
     * @type {number}
     * @memberof BulkAnalyticsResponse
     */
    'dataPoints'?: number;
    /**
     * 
     * @type {BulkMetadata}
     * @memberof BulkAnalyticsResponse
     */
    'metadata'?: BulkMetadata;
    /**
     * 
     * @type {number}
     * @memberof BulkAnalyticsResponse
     */
    'processingTimeMs'?: number;
}

