/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BulkGenerationResponseOperationsValueProgress } from './bulk-generation-response-operations-value-progress';

/**
 * 
 * @export
 * @interface BulkGenerationResponseOperationsValue
 */
export interface BulkGenerationResponseOperationsValue {
    /**
     * 
     * @type {string}
     * @memberof BulkGenerationResponseOperationsValue
     */
    'campaignId'?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkGenerationResponseOperationsValue
     */
    'status'?: BulkGenerationResponseOperationsValueStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof BulkGenerationResponseOperationsValue
     */
    'domainsGenerated'?: number;
    /**
     * 
     * @type {BulkGenerationResponseOperationsValueProgress}
     * @memberof BulkGenerationResponseOperationsValue
     */
    'progress'?: BulkGenerationResponseOperationsValueProgress;
}

/**
    * @export
    * @enum {string}
    */
export enum BulkGenerationResponseOperationsValueStatusEnum {
    pending = 'pending',
    running = 'running',
    completed = 'completed',
    failed = 'failed'
}


