/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BulkResourceStatusResponseResourceLimits } from './bulk-resource-status-response-resource-limits';

/**
 * 
 * @export
 * @interface BulkResourceStatusResponse
 */
export interface BulkResourceStatusResponse {
    /**
     * 
     * @type {number}
     * @memberof BulkResourceStatusResponse
     */
    'activeOperations'?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkResourceStatusResponse
     */
    'availablePersonas'?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkResourceStatusResponse
     */
    'availableProxies'?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkResourceStatusResponse
     */
    'cpuUsage'?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkResourceStatusResponse
     */
    'maxConcurrent'?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkResourceStatusResponse
     */
    'memoryUsage'?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkResourceStatusResponse
     */
    'networkUsage'?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkResourceStatusResponse
     */
    'queuedOperations'?: number;
    /**
     * 
     * @type {BulkResourceStatusResponseResourceLimits}
     * @memberof BulkResourceStatusResponse
     */
    'resourceLimits'?: BulkResourceStatusResponseResourceLimits;
}

