/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BulkHTTPValidationRequestOperationsInnerValidationConfig } from './bulk-httpvalidation-request-operations-inner-validation-config';

/**
 * 
 * @export
 * @interface BulkHTTPValidationRequestOperationsInner
 */
export interface BulkHTTPValidationRequestOperationsInner {
    /**
     * 
     * @type {string}
     * @memberof BulkHTTPValidationRequestOperationsInner
     */
    'campaignId': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkHTTPValidationRequestOperationsInner
     */
    'personaIds': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkHTTPValidationRequestOperationsInner
     */
    'keywords': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BulkHTTPValidationRequestOperationsInner
     */
    'maxDomains'?: number;
    /**
     * 
     * @type {BulkHTTPValidationRequestOperationsInnerValidationConfig}
     * @memberof BulkHTTPValidationRequestOperationsInner
     */
    'validationConfig'?: BulkHTTPValidationRequestOperationsInnerValidationConfig;
}

