/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BulkAnalyticsResponseAnalytics } from './bulk-analytics-response-analytics';

/**
 * 
 * @export
 * @interface BulkAnalyticsResponse
 */
export interface BulkAnalyticsResponse {
    /**
     * 
     * @type {string}
     * @memberof BulkAnalyticsResponse
     */
    'operationId': string;
    /**
     * 
     * @type {string}
     * @memberof BulkAnalyticsResponse
     */
    'status': BulkAnalyticsResponseStatusEnum;
    /**
     * 
     * @type {BulkAnalyticsResponseAnalytics}
     * @memberof BulkAnalyticsResponse
     */
    'analytics'?: BulkAnalyticsResponseAnalytics;
    /**
     * 
     * @type {number}
     * @memberof BulkAnalyticsResponse
     */
    'processedCampaigns': number;
    /**
     * 
     * @type {string}
     * @memberof BulkAnalyticsResponse
     */
    'estimatedCompletion'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum BulkAnalyticsResponseStatusEnum {
    initiated = 'initiated',
    pending = 'pending',
    running = 'running',
    completed = 'completed'
}


