/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BulkQueryMetadata } from './bulk-query-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { DatabaseQueryResult } from './database-query-result';

/**
 * 
 * @export
 * @interface BulkDatabaseQueryResponse
 */
export interface BulkDatabaseQueryResponse {
    /**
     * 
     * @type {BulkQueryMetadata}
     * @memberof BulkDatabaseQueryResponse
     */
    'metadata'?: BulkQueryMetadata;
    /**
     * 
     * @type {{ [key: string]: DatabaseQueryResult; }}
     * @memberof BulkDatabaseQueryResponse
     */
    'results'?: { [key: string]: DatabaseQueryResult; };
    /**
     * 
     * @type {number}
     * @memberof BulkDatabaseQueryResponse
     */
    'totalCount'?: number;
}

