/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BulkDNSValidationRequestOperationsInner } from './bulk-dnsvalidation-request-operations-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { BulkDNSValidationRequestStealth } from './bulk-dnsvalidation-request-stealth';

/**
 * 
 * @export
 * @interface BulkDNSValidationRequest
 */
export interface BulkDNSValidationRequest {
    /**
     * 
     * @type {Array<BulkDNSValidationRequestOperationsInner>}
     * @memberof BulkDNSValidationRequest
     */
    'operations': Array<BulkDNSValidationRequestOperationsInner>;
    /**
     * 
     * @type {number}
     * @memberof BulkDNSValidationRequest
     */
    'batchSize'?: number;
    /**
     * 
     * @type {BulkDNSValidationRequestStealth}
     * @memberof BulkDNSValidationRequest
     */
    'stealth'?: BulkDNSValidationRequestStealth;
}

