/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DomainGenerationResult } from './domain-generation-result';

/**
 * 
 * @export
 * @interface BulkDomainGenerationResponse
 */
export interface BulkDomainGenerationResponse {
    /**
     * 
     * @type {number}
     * @memberof BulkDomainGenerationResponse
     */
    'failedOps'?: number;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof BulkDomainGenerationResponse
     */
    'operationId'?: UUID;
    /**
     * 
     * @type {{ [key: string]: DomainGenerationResult; }}
     * @memberof BulkDomainGenerationResponse
     */
    'operations'?: { [key: string]: DomainGenerationResult; };
    /**
     * 
     * @type {number}
     * @memberof BulkDomainGenerationResponse
     */
    'processingTimeMs'?: number;
    /**
     * 
     * @type {string}
     * @memberof BulkDomainGenerationResponse
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof BulkDomainGenerationResponse
     */
    'successfulOps'?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkDomainGenerationResponse
     */
    'totalGenerated'?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkDomainGenerationResponse
     */
    'totalRequested'?: number;
}

