/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BulkOperationListRequest
 */
export interface BulkOperationListRequest {
    /**
     * 
     * @type {string}
     * @memberof BulkOperationListRequest
     */
    'endTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof BulkOperationListRequest
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkOperationListRequest
     */
    'offset'?: number;
    /**
     * 
     * @type {string}
     * @memberof BulkOperationListRequest
     */
    'startTime'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkOperationListRequest
     */
    'status'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkOperationListRequest
     */
    'type'?: Array<string>;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof BulkOperationListRequest
     */
    'userId'?: UUID;
}

