/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiErrorInfo } from './api-error-info';
// May contain unused imports in some cases
// @ts-ignore
import type { ApiMetadata } from './api-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { Data } from './data';
// May contain unused imports in some cases
// @ts-ignore
import type { GithubComFntelecomllcStudioBackendInternalModelsBulkValidationResponse } from './github-com-fntelecomllc-studio-backend-internal-models-bulk-validation-response';

/**
 * @type BulkValidateDNS200Response
 * Standard API response envelope used by all endpoints
 * @export
 */
export type BulkValidateDNS200Response = Data;


