/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BusinessKPIs
 */
export interface BusinessKPIs {
    /**
     * 
     * @type {number}
     * @memberof BusinessKPIs
     */
    'competitiveAdvantage'?: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessKPIs
     */
    'conversionRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessKPIs
     */
    'costPerLead'?: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessKPIs
     */
    'customerAcquisitionCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessKPIs
     */
    'customerLifetimeValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessKPIs
     */
    'leadGenerationRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessKPIs
     */
    'leadQualityScore'?: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessKPIs
     */
    'marketPenetrationRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessKPIs
     */
    'revenuePerOperation'?: number;
}

