/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CampaignDomainsListResponseAggregates } from './campaign-domains-list-response-aggregates';
// May contain unused imports in some cases
// @ts-ignore
import type { DomainListItem } from './domain-list-item';
// May contain unused imports in some cases
// @ts-ignore
import type { ExtendedPageInfo } from './extended-page-info';

/**
 * 
 * @export
 * @interface CampaignDomainsListResponse
 */
export interface CampaignDomainsListResponse {
  /**
   * 
   * @memberof CampaignDomainsListResponse
   */
  'campaignId': 
        
          
          string
    ;
  /**
   * 
   * @memberof CampaignDomainsListResponse
   */
  'items': 
        
          
          Array<DomainListItem>
    ;
  /**
   * 
   * @memberof CampaignDomainsListResponse
   */
  'total': 
        
          
          number
    ;
  /**
   * 
   * @memberof CampaignDomainsListResponse
   */
  'aggregates'?: 
        
          
          CampaignDomainsListResponseAggregates
    ;
  /**
   * 
   * @memberof CampaignDomainsListResponse
   */
  'pageInfo'?: 
        
          
          ExtendedPageInfo
    ;
}


