/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CampaignClassificationsResponseCounts
 */
export interface CampaignClassificationsResponseCounts {
    /**
     * 
     * @type {number}
     * @memberof CampaignClassificationsResponseCounts
     */
    'highPotential': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignClassificationsResponseCounts
     */
    'emerging': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignClassificationsResponseCounts
     */
    'atRisk': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignClassificationsResponseCounts
     */
    'leadCandidate': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignClassificationsResponseCounts
     */
    'lowValue': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignClassificationsResponseCounts
     */
    'other': number;
}

