/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Canonical campaign phase identifier
 * @export
 * @enum {string}
 */

export enum CampaignPhaseEnum {
    discovery = 'discovery',
    validation = 'validation',
    extraction = 'extraction',
    analysis = 'analysis'
}



