/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CampaignPhasesStatusResponsePhasesInner
 */
export interface CampaignPhasesStatusResponsePhasesInner {
    /**
     * 
     * @type {string}
     * @memberof CampaignPhasesStatusResponsePhasesInner
     */
    'phase': CampaignPhasesStatusResponsePhasesInnerPhaseEnum;
    /**
     * 
     * @type {string}
     * @memberof CampaignPhasesStatusResponsePhasesInner
     */
    'status': CampaignPhasesStatusResponsePhasesInnerStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CampaignPhasesStatusResponsePhasesInner
     */
    'progressPercentage': number;
    /**
     * 
     * @type {string}
     * @memberof CampaignPhasesStatusResponsePhasesInner
     */
    'startedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignPhasesStatusResponsePhasesInner
     */
    'completedAt'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum CampaignPhasesStatusResponsePhasesInnerPhaseEnum {
    generation = 'generation',
    dns = 'dns',
    http = 'http',
    analysis = 'analysis',
    leads = 'leads'
}
/**
    * @export
    * @enum {string}
    */
export enum CampaignPhasesStatusResponsePhasesInnerStatusEnum {
    not_started = 'not_started',
    ready = 'ready',
    configured = 'configured',
    in_progress = 'in_progress',
    paused = 'paused',
    completed = 'completed',
    failed = 'failed'
}


