/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CampaignDomainsListResponseAggregatesDns } from './campaign-domains-list-response-aggregates-dns';
// May contain unused imports in some cases
// @ts-ignore
import type { CampaignDomainsListResponseAggregatesLead } from './campaign-domains-list-response-aggregates-lead';

/**
 * Domain status aggregates sourced from counters table (Phase A optimization)
 * @export
 * @interface CampaignDomainsListResponseAggregates
 */
export interface CampaignDomainsListResponseAggregates {
  /**
   * 
   * @memberof CampaignDomainsListResponseAggregates
   */
  'dns'?: 
        
          
          CampaignDomainsListResponseAggregatesDns
    ;
  /**
   * 
   * @memberof CampaignDomainsListResponseAggregates
   */
  'http'?: 
        
          
          CampaignDomainsListResponseAggregatesDns
    ;
  /**
   * 
   * @memberof CampaignDomainsListResponseAggregates
   */
  'lead'?: 
        
          
          CampaignDomainsListResponseAggregatesLead
    ;
}


