/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CampaignsPhaseConfigsList200ResponseAllOfData
 */
export interface CampaignsPhaseConfigsList200ResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof CampaignsPhaseConfigsList200ResponseAllOfData
     */
    'campaignId'?: string;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof CampaignsPhaseConfigsList200ResponseAllOfData
     */
    'configsPresent'?: { [key: string]: boolean; };
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof CampaignsPhaseConfigsList200ResponseAllOfData
     */
    'configs'?: { [key: string]: object; };
}

