/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CampaignProgressResponseOverall
 */
export interface CampaignProgressResponseOverall {
    /**
     * 
     * @type {string}
     * @memberof CampaignProgressResponseOverall
     */
    'status'?: CampaignProgressResponseOverallStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CampaignProgressResponseOverall
     */
    'percentComplete'?: number;
    /**
     * 
     * @type {number}
     * @memberof CampaignProgressResponseOverall
     */
    'totalDomains'?: number;
    /**
     * 
     * @type {number}
     * @memberof CampaignProgressResponseOverall
     */
    'processedDomains'?: number;
    /**
     * 
     * @type {number}
     * @memberof CampaignProgressResponseOverall
     */
    'successfulDomains'?: number;
    /**
     * 
     * @type {number}
     * @memberof CampaignProgressResponseOverall
     */
    'failedDomains'?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum CampaignProgressResponseOverallStatusEnum {
    draft = 'draft',
    running = 'running',
    paused = 'paused',
    completed = 'completed',
    failed = 'failed',
    cancelled = 'cancelled'
}


