/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CampaignPhase
 */
export interface CampaignPhase {
    /**
     * Unique identifier
     * @type {string}
     * @memberof CampaignPhase
     */
    'campaignId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignPhase
     */
    'completedAt'?: string;
    /**
     * Phase configuration (JSON storage for phase-specific params)
     * @type {object}
     * @memberof CampaignPhase
     */
    'configuration'?: object;
    /**
     * Audit fields
     * @type {string}
     * @memberof CampaignPhase
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignPhase
     */
    'errorMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignPhase
     */
    'failedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof CampaignPhase
     */
    'failedItems'?: number;
    /**
     * Unique identifier
     * @type {string}
     * @memberof CampaignPhase
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignPhase
     */
    'pausedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof CampaignPhase
     */
    'phaseOrder'?: number;
    /**
     * 
     * @type {string}
     * @memberof CampaignPhase
     */
    'phaseType'?: CampaignPhasePhaseTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CampaignPhase
     */
    'processedItems'?: number;
    /**
     * 
     * @type {number}
     * @memberof CampaignPhase
     */
    'progressPercentage'?: number;
    /**
     * Phase lifecycle timestamps
     * @type {string}
     * @memberof CampaignPhase
     */
    'startedAt'?: string;
    /**
     * Phase execution status
     * @type {string}
     * @memberof CampaignPhase
     */
    'status'?: CampaignPhaseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CampaignPhase
     */
    'successfulItems'?: number;
    /**
     * Phase execution counters
     * @type {number}
     * @memberof CampaignPhase
     */
    'totalItems'?: number;
    /**
     * 
     * @type {string}
     * @memberof CampaignPhase
     */
    'updatedAt'?: string;
}

export const CampaignPhasePhaseTypeEnum = {
    DomainGeneration: 'domain_generation',
    DnsValidation: 'dns_validation',
    HttpKeywordValidation: 'http_keyword_validation',
    Analysis: 'analysis'
} as const;

export type CampaignPhasePhaseTypeEnum = typeof CampaignPhasePhaseTypeEnum[keyof typeof CampaignPhasePhaseTypeEnum];
export const CampaignPhaseStatusEnum = {
    NotStarted: 'not_started',
    Ready: 'ready',
    Configured: 'configured',
    InProgress: 'in_progress',
    Paused: 'paused',
    Completed: 'completed',
    Failed: 'failed'
} as const;

export type CampaignPhaseStatusEnum = typeof CampaignPhaseStatusEnum[keyof typeof CampaignPhaseStatusEnum];


