/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enumerated server-sent campaign event names.
 * @export
 * @enum {string}
 */

export enum CampaignSseEventType {
    analysis_reuse_enrichment = 'analysis_reuse_enrichment',
    analysis_failed = 'analysis_failed',
    campaign_progress = 'campaign_progress',
    counters_reconciled = 'counters_reconciled',
    domain_generated = 'domain_generated',
    domain_validated = 'domain_validated',
    phase_started = 'phase_started',
    phase_completed = 'phase_completed',
    phase_failed = 'phase_failed'
}



