/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CampaignClassificationsResponseCounts
 */
export interface CampaignClassificationsResponseCounts {
  /**
   * 
   * @memberof CampaignClassificationsResponseCounts
   */
  'highPotential': 
        
          
          number
    ;
  /**
   * 
   * @memberof CampaignClassificationsResponseCounts
   */
  'emerging': 
        
          
          number
    ;
  /**
   * 
   * @memberof CampaignClassificationsResponseCounts
   */
  'atRisk': 
        
          
          number
    ;
  /**
   * 
   * @memberof CampaignClassificationsResponseCounts
   */
  'leadCandidate': 
        
          
          number
    ;
  /**
   * 
   * @memberof CampaignClassificationsResponseCounts
   */
  'lowValue': 
        
          
          number
    ;
  /**
   * 
   * @memberof CampaignClassificationsResponseCounts
   */
  'other': 
        
          
          number
    ;
}


