/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * KPI and warning component metrics for a campaign
 * @export
 * @interface CampaignMetricsResponse
 */
export interface CampaignMetricsResponse {
    /**
     * 
     * @type {number}
     * @memberof CampaignMetricsResponse
     */
    'highPotential': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignMetricsResponse
     */
    'leads': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignMetricsResponse
     */
    'keywordCoveragePct': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignMetricsResponse
     */
    'avgRichness': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignMetricsResponse
     */
    'warningRatePct': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignMetricsResponse
     */
    'medianGain': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignMetricsResponse
     */
    'stuffing': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignMetricsResponse
     */
    'repetition': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignMetricsResponse
     */
    'anchor': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignMetricsResponse
     */
    'totalAnalyzed': number;
}

