/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConfigWorkerConfig
 */
export interface ConfigWorkerConfig {
    /**
     * 
     * @type {number}
     * @memberof ConfigWorkerConfig
     */
    'batchSize'?: number;
    /**
     * Added
     * @type {number}
     * @memberof ConfigWorkerConfig
     */
    'dnsSubtaskConcurrency'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigWorkerConfig
     */
    'errorRetryDelaySeconds'?: number;
    /**
     * Added
     * @type {number}
     * @memberof ConfigWorkerConfig
     */
    'httpKeywordSubtaskConcurrency'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigWorkerConfig
     */
    'jobProcessingTimeoutMinutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigWorkerConfig
     */
    'maxJobRetries'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigWorkerConfig
     */
    'maxRetries'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigWorkerConfig
     */
    'numWorkers'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigWorkerConfig
     */
    'pollIntervalSeconds'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigWorkerConfig
     */
    'retryDelaySeconds'?: number;
}

