/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CountermeasureAnalysis
 */
export interface CountermeasureAnalysis {
    /**
     * 
     * @type {number}
     * @memberof CountermeasureAnalysis
     */
    'bypassSuccessRate'?: number;
    /**
     * 
     * @type {string}
     * @memberof CountermeasureAnalysis
     */
    'countermeasureName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CountermeasureAnalysis
     */
    'deploymentStatus'?: 'active' | 'inactive' | 'testing' | 'deprecated';
    /**
     * 
     * @type {number}
     * @memberof CountermeasureAnalysis
     */
    'effectivenessRating'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CountermeasureAnalysis
     */
    'maintenanceRequired'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CountermeasureAnalysis
     */
    'resourceUtilization'?: number;
    /**
     * 
     * @type {string}
     * @memberof CountermeasureAnalysis
     */
    'updateFrequency'?: 'realtime' | 'hourly' | 'daily' | 'weekly' | 'monthly';
}

/**
    * @export
    * @enum {string}
    */
// Enum CountermeasureAnalysisDeploymentStatusEnum converted to direct string literals in interface
/**
    * @export
    * @enum {string}
    */
// Enum CountermeasureAnalysisUpdateFrequencyEnum converted to direct string literals in interface


