/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DomainGenerationPhaseConfig } from './domain-generation-phase-config';

/**
 * 
 * @export
 * @interface CreateLeadGenerationCampaignRequest
 */
export interface CreateLeadGenerationCampaignRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateLeadGenerationCampaignRequest
     */
    'description'?: string;
    /**
     * 
     * @type {DomainGenerationPhaseConfig}
     * @memberof CreateLeadGenerationCampaignRequest
     */
    'domainConfig': DomainGenerationPhaseConfig;
    /**
     * 
     * @type {string}
     * @memberof CreateLeadGenerationCampaignRequest
     */
    'name': string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof CreateLeadGenerationCampaignRequest
     */
    'userId'?: UUID;
}

