/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Configuration fragment accepted at campaign creation time.
 * @export
 * @interface CreateCampaignConfiguration
 */
export interface CreateCampaignConfiguration {
  /**
   * 
   * @memberof CreateCampaignConfiguration
   */
  'generationStrategy'?: 
      'pattern' | 'list' | 'seed_keywords'
;
  /**
   * 
   * @memberof CreateCampaignConfiguration
   */
  'pattern'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof CreateCampaignConfiguration
   */
  'initialDomains'?: 
        
          
          Array<string>
    ;
  /**
   * 
   * @memberof CreateCampaignConfiguration
   */
  'seedKeywords'?: 
        
          
          Array<string>
    ;
}


