/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateScoringProfileRequest
 */
export interface CreateScoringProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateScoringProfileRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateScoringProfileRequest
     */
    'description'?: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof CreateScoringProfileRequest
     */
    'weights': { [key: string]: number; };
    /**
     * Optional explicit version; defaults to 1 if omitted
     * @type {number}
     * @memberof CreateScoringProfileRequest
     */
    'version'?: number;
}

