/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DNSValidationParams } from './dnsvalidation-params';
// May contain unused imports in some cases
// @ts-ignore
import type { DNSValidationPhaseConfig } from './dnsvalidation-phase-config';
// May contain unused imports in some cases
// @ts-ignore
import type { HTTPKeywordParams } from './httpkeyword-params';
// May contain unused imports in some cases
// @ts-ignore
import type { HTTPValidationPhaseConfig } from './httpvalidation-phase-config';

/**
 * 
 * @export
 * @interface CreateDomainGenerationCampaignRequest
 */
export interface CreateDomainGenerationCampaignRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'characterSet': string;
    /**
     * 
     * @type {string}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'constantString'?: string;
    /**
     * 
     * @type {DNSValidationPhaseConfig}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'dnsValidationConfig'?: DNSValidationPhaseConfig;
    /**
     * 
     * @type {DNSValidationParams}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'dnsValidationParams'?: DNSValidationParams;
    /**
     * 
     * @type {boolean}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'enableDnsValidation'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'enableHttpValidation'?: boolean;
    /**
     * 
     * @type {HTTPKeywordParams}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'httpKeywordParams'?: HTTPKeywordParams;
    /**
     * 
     * @type {HTTPValidationPhaseConfig}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'httpValidationConfig'?: HTTPValidationPhaseConfig;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'keywords': Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'launchSequence'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'maxResults': number;
    /**
     * 
     * @type {string}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'numDomainsToGenerate': number;
    /**
     * 
     * @type {string}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'patternType': CreateDomainGenerationCampaignRequestPatternTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'tld': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'tlds': Array<string>;
    /**
     * Unique identifier
     * @type {string}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'userId'?: string;
    /**
     * Domain generation fields
     * @type {number}
     * @memberof CreateDomainGenerationCampaignRequest
     */
    'variableLength': number;
}

export const CreateDomainGenerationCampaignRequestPatternTypeEnum = {
    Prefix: 'prefix',
    Suffix: 'suffix',
    Both: 'both'
} as const;

export type CreateDomainGenerationCampaignRequestPatternTypeEnum = typeof CreateDomainGenerationCampaignRequestPatternTypeEnum[keyof typeof CreateDomainGenerationCampaignRequestPatternTypeEnum];


