/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DashboardPosition } from './dashboard-position';
// May contain unused imports in some cases
// @ts-ignore
import type { DashboardSize } from './dashboard-size';

/**
 * 
 * @export
 * @interface DashboardSection
 */
export interface DashboardSection {
    /**
     * 
     * @type {boolean}
     * @memberof DashboardSection
     */
    'collapsible'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DashboardSection
     */
    'dataSource'?: string;
    /**
     * 
     * @type {DashboardPosition}
     * @memberof DashboardSection
     */
    'position'?: DashboardPosition;
    /**
     * 
     * @type {number}
     * @memberof DashboardSection
     */
    'refreshRate'?: number;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof DashboardSection
     */
    'sectionId'?: UUID;
    /**
     * 
     * @type {string}
     * @memberof DashboardSection
     */
    'sectionTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardSection
     */
    'sectionType'?: 'chart' | 'table' | 'metric' | 'alert' | 'summary';
    /**
     * 
     * @type {DashboardSize}
     * @memberof DashboardSection
     */
    'size'?: DashboardSize;
    /**
     * 
     * @type {boolean}
     * @memberof DashboardSection
     */
    'visible'?: boolean;
}

/**
    * @export
    * @enum {string}
    */
// Enum DashboardSectionSectionTypeEnum converted to direct string literals in interface


