/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Overall database statistics
 * @export
 * @interface DatabaseStats
 */
export interface DatabaseStats {
    /**
     * 
     * @type {number}
     * @memberof DatabaseStats
     */
    'totalTables'?: number;
    /**
     * 
     * @type {number}
     * @memberof DatabaseStats
     */
    'totalUsers'?: number;
    /**
     * 
     * @type {number}
     * @memberof DatabaseStats
     */
    'totalSessions'?: number;
    /**
     * 
     * @type {string}
     * @memberof DatabaseStats
     */
    'databaseSize'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseStats
     */
    'schemaVersion'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseStats
     */
    'uptime'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseStats
     */
    'version'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DatabaseStats
     */
    'isHealthy'?: boolean;
}

