/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DatabaseValue
 */
export interface DatabaseValue {
    /**
     * 
     * @type {string}
     * @memberof DatabaseValue
     */
    'stringValue'?: string;
    /**
     * 
     * @type {number}
     * @memberof DatabaseValue
     */
    'intValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof DatabaseValue
     */
    'floatValue'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DatabaseValue
     */
    'boolValue'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DatabaseValue
     */
    'isNull'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DatabaseValue
     */
    'rawValue'?: string;
}

