/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DataResponse
 */
export interface DataResponse {
    /**
     * 
     * @type {string}
     * @memberof DataResponse
     */
    'data'?: string;
    /**
     * 
     * @type {string}
     * @memberof DataResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DataResponse
     */
    'success'?: boolean;
}

