/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DebugNetworkLogIngestRequest
 */
export interface DebugNetworkLogIngestRequest {
    [key: string]: any;

    /**
     * ISO-8601 timestamp produced by the client
     * @type {string}
     * @memberof DebugNetworkLogIngestRequest
     */
    'timestamp': string;
    /**
     * Absolute or relative request URL observed by the browser
     * @type {string}
     * @memberof DebugNetworkLogIngestRequest
     */
    'url': string;
    /**
     * HTTP method used for the request
     * @type {string}
     * @memberof DebugNetworkLogIngestRequest
     */
    'method': string;
    /**
     * HTTP status code returned by the response
     * @type {number}
     * @memberof DebugNetworkLogIngestRequest
     */
    'status'?: number;
    /**
     * Whether the browser considered the response successful
     * @type {boolean}
     * @memberof DebugNetworkLogIngestRequest
     */
    'ok'?: boolean;
    /**
     * Duration of the request in milliseconds
     * @type {number}
     * @memberof DebugNetworkLogIngestRequest
     */
    'durationMs': number;
    /**
     * Error message captured when the request failed
     * @type {string}
     * @memberof DebugNetworkLogIngestRequest
     */
    'error'?: string;
    /**
     * Request headers observed by the browser
     * @type {{ [key: string]: string; }}
     * @memberof DebugNetworkLogIngestRequest
     */
    'requestHeaders'?: { [key: string]: string; };
    /**
     * Response headers observed by the browser
     * @type {{ [key: string]: string; }}
     * @memberof DebugNetworkLogIngestRequest
     */
    'responseHeaders'?: { [key: string]: string; };
}

