/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DiscoveryLineageCampaignOffsetRange } from './discovery-lineage-campaign-offset-range';
// May contain unused imports in some cases
// @ts-ignore
import type { DiscoveryLineageCampaignStats } from './discovery-lineage-campaign-stats';

/**
 * Campaign in the discovery lineage with stats
 * @export
 * @interface DiscoveryLineageCampaign
 */
export interface DiscoveryLineageCampaign {
  /**
   * 
   * @memberof DiscoveryLineageCampaign
   */
  'id': 
        
          
          string
    ;
  /**
   * 
   * @memberof DiscoveryLineageCampaign
   */
  'name': 
        
          
          string
    ;
  /**
   * 
   * @memberof DiscoveryLineageCampaign
   */
  'createdAt': 
        
          
          string
    ;
  /**
   * 
   * @memberof DiscoveryLineageCampaign
   */
  'offsetRange'?: 
        
          
          DiscoveryLineageCampaignOffsetRange
    ;
  /**
   * 
   * @memberof DiscoveryLineageCampaign
   */
  'stats': 
        
          
          DiscoveryLineageCampaignStats
    ;
}


