/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DnsValidationParams
 */
export interface DnsValidationParams {
    /**
     * 
     * @type {number}
     * @memberof DnsValidationParams
     */
    'batchSize'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DnsValidationParams
     */
    'personaIds'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DnsValidationParams
     */
    'processingSpeedPerMinute'?: number;
    /**
     * 
     * @type {number}
     * @memberof DnsValidationParams
     */
    'retryAttempts'?: number;
    /**
     * 
     * @type {number}
     * @memberof DnsValidationParams
     */
    'rotationIntervalSeconds'?: number;
    /**
     * 
     * @type {string}
     * @memberof DnsValidationParams
     */
    'sourceCampaignId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DnsValidationParams
     */
    'sourceGenerationCampaignId'?: string;
}

