/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DNS validator configuration
 * @export
 * @interface DNSConfig
 */
export interface DNSConfig {
    /**
     * Concurrent queries per domain
     * @type {number}
     * @memberof DNSConfig
     */
    'concurrentQueriesPerDomain'?: number;
    /**
     * Maximum concurrent goroutines
     * @type {number}
     * @memberof DNSConfig
     */
    'maxConcurrentGoroutines'?: number;
    /**
     * Maximum domains per request
     * @type {number}
     * @memberof DNSConfig
     */
    'maxDomainsPerRequest'?: number;
    /**
     * Maximum query delay in milliseconds
     * @type {number}
     * @memberof DNSConfig
     */
    'queryDelayMaxMs'?: number;
    /**
     * Minimum query delay in milliseconds
     * @type {number}
     * @memberof DNSConfig
     */
    'queryDelayMinMs'?: number;
    /**
     * DNS query timeout in seconds
     * @type {number}
     * @memberof DNSConfig
     */
    'queryTimeoutSeconds'?: number;
    /**
     * Rate limit burst capacity
     * @type {number}
     * @memberof DNSConfig
     */
    'rateLimitBurst'?: number;
    /**
     * Rate limit in queries per second
     * @type {number}
     * @memberof DNSConfig
     */
    'rateLimitDps'?: number;
    /**
     * Strategy for selecting DNS resolvers
     * @type {string}
     * @memberof DNSConfig
     */
    'resolverStrategy'?: DNSConfigResolverStrategyEnum;
    /**
     * DNS resolver IP addresses
     * @type {Array<string>}
     * @memberof DNSConfig
     */
    'resolvers'?: Array<string>;
    /**
     * Preferred order of resolvers
     * @type {Array<string>}
     * @memberof DNSConfig
     */
    'resolversPreferredOrder'?: Array<string>;
    /**
     * Weighted resolver configuration
     * @type {{ [key: string]: number; }}
     * @memberof DNSConfig
     */
    'resolversWeighted'?: { [key: string]: number; };
    /**
     * Use system DNS resolvers
     * @type {boolean}
     * @memberof DNSConfig
     */
    'useSystemResolvers'?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum DNSConfigResolverStrategyEnum {
    RoundRobin = 'round_robin',
    Random = 'random',
    Weighted = 'weighted',
    Priority = 'priority'
}


