/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DNS validator configuration
 * @export
 * @interface DNSValidatorConfigJSON
 */
export interface DNSValidatorConfigJSON {
  /**
   * Custom DNS resolver endpoints
   * @memberof DNSValidatorConfigJSON
   */
  'resolvers'?: 
        
          
          Array<string>
    ;
  /**
   * Query timeout in milliseconds
   * @memberof DNSValidatorConfigJSON
   */
  'timeoutMs'?: 
        
          
          number
    ;
  /**
   * Number of retry attempts
   * @memberof DNSValidatorConfigJSON
   */
  'retries'?: 
        
          
          number
    ;
}


