/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DomainGenerationOperation
 */
export interface DomainGenerationOperation {
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof DomainGenerationOperation
     */
    'campaignId': UUID;
    /**
     * 
     * @type {object}
     * @memberof DomainGenerationOperation
     */
    'config': object;
    /**
     * 
     * @type {number}
     * @memberof DomainGenerationOperation
     */
    'maxDomains'?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainGenerationOperation
     */
    'startFrom'?: number;
}

