/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Parameters for domain generation campaigns
 * @export
 * @interface DomainGenerationParams
 */
export interface DomainGenerationParams {
    /**
     * Character set for generation
     * @type {string}
     * @memberof DomainGenerationParams
     */
    'characterSet': string;
    /**
     * Constant string portion
     * @type {string}
     * @memberof DomainGenerationParams
     */
    'constantString': string;
    /**
     * Number of domains to generate
     * @type {number}
     * @memberof DomainGenerationParams
     */
    'numDomainsToGenerate'?: number;
    /**
     * Pattern type for domain generation
     * @type {string}
     * @memberof DomainGenerationParams
     */
    'patternType': DomainGenerationParamsPatternTypeEnum;
    /**
     * Top-level domain
     * @type {string}
     * @memberof DomainGenerationParams
     */
    'tld': string;
    /**
     * Length of variable portion
     * @type {number}
     * @memberof DomainGenerationParams
     */
    'variableLength': number;
}

export const DomainGenerationParamsPatternTypeEnum = {
    PrefixVariable: 'prefix_variable',
    SuffixVariable: 'suffix_variable',
    BothVariable: 'both_variable'
} as const;

export type DomainGenerationParamsPatternTypeEnum = typeof DomainGenerationParamsPatternTypeEnum[keyof typeof DomainGenerationParamsPatternTypeEnum];


