/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DomainGenerationConfig
 */
export interface DomainGenerationConfig {
    /**
     * 
     * @type {number}
     * @memberof DomainGenerationConfig
     */
    'batchSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainGenerationConfig
     */
    'characterSet': string;
    /**
     * 
     * @type {string}
     * @memberof DomainGenerationConfig
     */
    'constantString': string;
    /**
     * 
     * @type {number}
     * @memberof DomainGenerationConfig
     */
    'numDomainsToGenerate'?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainGenerationConfig
     */
    'patternType': DomainGenerationConfigPatternTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainGenerationConfig
     */
    'tlds': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DomainGenerationConfig
     */
    'variableLength': number;
}

export const DomainGenerationConfigPatternTypeEnum = {
    Prefix: 'prefix',
    Suffix: 'suffix',
    Both: 'both'
} as const;

export type DomainGenerationConfigPatternTypeEnum = typeof DomainGenerationConfigPatternTypeEnum[keyof typeof DomainGenerationConfigPatternTypeEnum];


