/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CampaignData } from './campaign-data';

/**
 * 
 * @export
 * @interface EnrichedCampaignData
 */
export interface EnrichedCampaignData {
    /**
     * 
     * @type {CampaignData}
     * @memberof EnrichedCampaignData
     */
    'campaign'?: CampaignData;
    /**
     * 
     * @type {Array<string>}
     * @memberof EnrichedCampaignData
     */
    'dnsValidatedDomains'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EnrichedCampaignData
     */
    'domains'?: Array<string>;
    /**
     * 
     * @type {Array<object>}
     * @memberof EnrichedCampaignData
     */
    'httpKeywordResults'?: Array<object>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EnrichedCampaignData
     */
    'leads'?: Array<string>;
}

