/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EnterpriseProxyStrategy
 */
export interface EnterpriseProxyStrategy {
    /**
     * 
     * @type {Array<string>}
     * @memberof EnterpriseProxyStrategy
     */
    'backupProxyPools'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof EnterpriseProxyStrategy
     */
    'failoverThreshold'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EnterpriseProxyStrategy
     */
    'geoTargeting'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EnterpriseProxyStrategy
     */
    'healthCheckInterval'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof EnterpriseProxyStrategy
     */
    'proxyPools'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof EnterpriseProxyStrategy
     */
    'proxyQualityFiltering'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseProxyStrategy
     */
    'proxyRotationRate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseProxyStrategy
     */
    'strategy'?: string;
}

