/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EventStoreRecord
 */
export interface EventStoreRecord {
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof EventStoreRecord
     */
    'aggregateId'?: UUID;
    /**
     * 
     * @type {string}
     * @memberof EventStoreRecord
     */
    'aggregateType'?: string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof EventStoreRecord
     */
    'causationId'?: UUID;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof EventStoreRecord
     */
    'correlationId'?: UUID;
    /**
     * 
     * @type {object}
     * @memberof EventStoreRecord
     */
    'eventData'?: object;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof EventStoreRecord
     */
    'eventId'?: UUID;
    /**
     * 
     * @type {string}
     * @memberof EventStoreRecord
     */
    'eventType'?: string;
    /**
     * 
     * @type {number}
     * @memberof EventStoreRecord
     */
    'eventVersion'?: number;
    /**
     * 
     * @type {number}
     * @memberof EventStoreRecord
     */
    'globalPosition'?: number;
    /**
     * 
     * @type {number}
     * @memberof EventStoreRecord
     */
    'id'?: number;
    /**
     * 
     * @type {object}
     * @memberof EventStoreRecord
     */
    'metadata'?: object;
    /**
     * 
     * @type {string}
     * @memberof EventStoreRecord
     */
    'occurredAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof EventStoreRecord
     */
    'recordedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof EventStoreRecord
     */
    'streamPosition'?: number;
}

