/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExtractedContentAnalysis
 */
export interface ExtractedContentAnalysis {
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtractedContentAnalysis
     */
    'advancedKeywords'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtractedContentAnalysis
     */
    'categories'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ExtractedContentAnalysis
     */
    'sentiment'?: 'Positive' | 'Negative' | 'Neutral';
    /**
     * 
     * @type {string}
     * @memberof ExtractedContentAnalysis
     */
    'summary'?: string;
}

/**
    * @export
    * @enum {string}
    */
// Enum ExtractedContentAnalysisSentimentEnum converted to direct string literals in interface


