/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExtractedContentAnalysis } from './extracted-content-analysis';

/**
 * 
 * @export
 * @interface ExtractedContentItem
 */
export interface ExtractedContentItem {
    /**
     * 
     * @type {ExtractedContentAnalysis}
     * @memberof ExtractedContentItem
     */
    'advancedAnalysis'?: ExtractedContentAnalysis;
    /**
     * 
     * @type {string}
     * @memberof ExtractedContentItem
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtractedContentItem
     */
    'previousCampaignId'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtractedContentItem
     */
    'similarityScore'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtractedContentItem
     */
    'sourceUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtractedContentItem
     */
    'text'?: string;
}

