/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Forecast data point with optional probabilistic quantiles
 * @export
 * @interface ForecastProbabilisticPoint
 */
export interface ForecastProbabilisticPoint {
    /**
     * 
     * @type {string}
     * @memberof ForecastProbabilisticPoint
     */
    'timestamp': string;
    /**
     * 
     * @type {number}
     * @memberof ForecastProbabilisticPoint
     */
    'value': number;
    /**
     * 
     * @type {number}
     * @memberof ForecastProbabilisticPoint
     */
    'lower'?: number;
    /**
     * 
     * @type {number}
     * @memberof ForecastProbabilisticPoint
     */
    'upper'?: number;
    /**
     * 
     * @type {number}
     * @memberof ForecastProbabilisticPoint
     */
    'p10'?: number;
    /**
     * 
     * @type {number}
     * @memberof ForecastProbabilisticPoint
     */
    'p50'?: number;
    /**
     * 
     * @type {number}
     * @memberof ForecastProbabilisticPoint
     */
    'p90'?: number;
    /**
     * 
     * @type {number}
     * @memberof ForecastProbabilisticPoint
     */
    'confidence'?: number;
    /**
     * 
     * @type {string}
     * @memberof ForecastProbabilisticPoint
     */
    'metricKey'?: string;
}

