/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GeneratedDomain } from './generated-domain';

/**
 * Paginated list of generated domains
 * @export
 * @interface GeneratedDomainsResponse
 */
export interface GeneratedDomainsResponse {
    /**
     * List of generated domains
     * @type {Array<GeneratedDomain>}
     * @memberof GeneratedDomainsResponse
     */
    'domains': Array<GeneratedDomain>;
    /**
     * Number of items per page
     * @type {number}
     * @memberof GeneratedDomainsResponse
     */
    'limit': number;
    /**
     * Current page number
     * @type {number}
     * @memberof GeneratedDomainsResponse
     */
    'page': number;
    /**
     * Total number of domains
     * @type {number}
     * @memberof GeneratedDomainsResponse
     */
    'total': number;
}

