/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GeneratedDomain
 */
export interface GeneratedDomain {
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'dnsIp'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'dnsStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'domainName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'generatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'generationCampaignId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'httpKeywords'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'httpStatus'?: string;
    /**
     * 
     * @type {number}
     * @memberof GeneratedDomain
     */
    'httpStatusCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'httpTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'lastValidatedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof GeneratedDomain
     */
    'leadScore'?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneratedDomain
     */
    'offsetIndex'?: number;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'sourceKeyword'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'sourcePattern'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedDomain
     */
    'tld'?: string;
}

