/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DomainGenerationConfig } from './domain-generation-config';

/**
 * 
 * @export
 * @interface GenerateDomainsRequest
 */
export interface GenerateDomainsRequest {
    /**
     * Unique identifier
     * @type {string}
     * @memberof GenerateDomainsRequest
     */
    'campaign_id'?: string;
    /**
     * 
     * @type {DomainGenerationConfig}
     * @memberof GenerateDomainsRequest
     */
    'config'?: DomainGenerationConfig;
}

