/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubComFntelecomllcStudioBackendInternalModelsRequiredResources } from './github-com-fntelecomllc-studio-backend-internal-models-required-resources';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsBulkCampaignOperationConfig } from './models-bulk-campaign-operation-config';

/**
 * 
 * @export
 * @interface GithubComFntelecomllcStudioBackendInternalModelsResourceOperation
 */
export interface GithubComFntelecomllcStudioBackendInternalModelsResourceOperation {
    /**
     * 
     * @type {string}
     * @memberof GithubComFntelecomllcStudioBackendInternalModelsResourceOperation
     */
    'campaignId': string;
    /**
     * 
     * @type {ModelsBulkCampaignOperationConfig}
     * @memberof GithubComFntelecomllcStudioBackendInternalModelsResourceOperation
     */
    'config'?: ModelsBulkCampaignOperationConfig;
    /**
     * 
     * @type {string}
     * @memberof GithubComFntelecomllcStudioBackendInternalModelsResourceOperation
     */
    'priority'?: 'low' | 'normal' | 'high' | 'critical';
    /**
     * 
     * @type {GithubComFntelecomllcStudioBackendInternalModelsRequiredResources}
     * @memberof GithubComFntelecomllcStudioBackendInternalModelsResourceOperation
     */
    'resources'?: GithubComFntelecomllcStudioBackendInternalModelsRequiredResources;
    /**
     * 
     * @type {string}
     * @memberof GithubComFntelecomllcStudioBackendInternalModelsResourceOperation
     */
    'type': 'domain_generation' | 'dns_validation' | 'http_validation' | 'analytics';
}

/**
    * @export
    * @enum {string}
    */
// Enum GithubComFntelecomllcStudioBackendInternalModelsResourceOperationPriorityEnum converted to direct string literals in interface
/**
    * @export
    * @enum {string}
    */
// Enum GithubComFntelecomllcStudioBackendInternalModelsResourceOperationTypeEnum converted to direct string literals in interface


