/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsTimeSeriesMetricValues } from './models-time-series-metric-values';

/**
 * 
 * @export
 * @interface GithubComFntelecomllcStudioBackendInternalModelsTimeSeriesPoint
 */
export interface GithubComFntelecomllcStudioBackendInternalModelsTimeSeriesPoint {
    /**
     * 
     * @type {string}
     * @memberof GithubComFntelecomllcStudioBackendInternalModelsTimeSeriesPoint
     */
    'timestamp'?: string;
    /**
     * 
     * @type {ModelsTimeSeriesMetricValues}
     * @memberof GithubComFntelecomllcStudioBackendInternalModelsTimeSeriesPoint
     */
    'values'?: ModelsTimeSeriesMetricValues;
}

