/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubComFntelecomllcStudioBackendInternalModelsBulkMetadata } from './github-com-fntelecomllc-studio-backend-internal-models-bulk-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { GithubComFntelecomllcStudioBackendInternalModelsBulkOperationStatus } from './github-com-fntelecomllc-studio-backend-internal-models-bulk-operation-status';

/**
 * 
 * @export
 * @interface GithubComFntelecomllcStudioBackendInternalModelsBulkOperationListResponse
 */
export interface GithubComFntelecomllcStudioBackendInternalModelsBulkOperationListResponse {
    /**
     * 
     * @type {GithubComFntelecomllcStudioBackendInternalModelsBulkMetadata}
     * @memberof GithubComFntelecomllcStudioBackendInternalModelsBulkOperationListResponse
     */
    'metadata'?: GithubComFntelecomllcStudioBackendInternalModelsBulkMetadata;
    /**
     * 
     * @type {Array<GithubComFntelecomllcStudioBackendInternalModelsBulkOperationStatus>}
     * @memberof GithubComFntelecomllcStudioBackendInternalModelsBulkOperationListResponse
     */
    'operations'?: Array<GithubComFntelecomllcStudioBackendInternalModelsBulkOperationStatus>;
    /**
     * 
     * @type {number}
     * @memberof GithubComFntelecomllcStudioBackendInternalModelsBulkOperationListResponse
     */
    'totalCount'?: number;
}

