/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * HTTP validator configuration
 * @export
 * @interface HTTPConfig
 */
export interface HTTPConfig {
    /**
     * Allow insecure TLS connections
     * @type {boolean}
     * @memberof HTTPConfig
     */
    'allowInsecureTLS'?: boolean;
    /**
     * Default HTTP headers
     * @type {{ [key: string]: string; }}
     * @memberof HTTPConfig
     */
    'defaultHeaders'?: { [key: string]: string; };
    /**
     * Default User-Agent string for HTTP requests
     * @type {string}
     * @memberof HTTPConfig
     */
    'defaultUserAgent'?: string;
    /**
     * Whether to follow HTTP redirects
     * @type {boolean}
     * @memberof HTTPConfig
     */
    'followRedirects'?: boolean;
    /**
     * Maximum bytes to read from response body
     * @type {number}
     * @memberof HTTPConfig
     */
    'maxBodyReadBytes'?: number;
    /**
     * Maximum concurrent goroutines
     * @type {number}
     * @memberof HTTPConfig
     */
    'maxConcurrentGoroutines'?: number;
    /**
     * Maximum domains per request
     * @type {number}
     * @memberof HTTPConfig
     */
    'maxDomainsPerRequest'?: number;
    /**
     * Maximum number of redirects to follow
     * @type {number}
     * @memberof HTTPConfig
     */
    'maxRedirects'?: number;
    /**
     * Rate limit burst capacity
     * @type {number}
     * @memberof HTTPConfig
     */
    'rateLimitBurst'?: number;
    /**
     * Rate limit in requests per second
     * @type {number}
     * @memberof HTTPConfig
     */
    'rateLimitDps'?: number;
    /**
     * Request timeout in seconds
     * @type {number}
     * @memberof HTTPConfig
     */
    'requestTimeoutSeconds'?: number;
    /**
     * List of User-Agent strings to rotate through
     * @type {Array<string>}
     * @memberof HTTPConfig
     */
    'userAgents'?: Array<string>;
}

