/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InteractiveElement
 */
export interface InteractiveElement {
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof InteractiveElement
     */
    'configuration'?: { [key: string]: object; };
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof InteractiveElement
     */
    'elementId'?: UUID;
    /**
     * 
     * @type {string}
     * @memberof InteractiveElement
     */
    'elementType'?: 'filter' | 'drill_down' | 'zoom' | 'pan' | 'select' | 'highlight';
    /**
     * 
     * @type {boolean}
     * @memberof InteractiveElement
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof InteractiveElement
     */
    'eventTriggers'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InteractiveElement
     */
    'targetCharts'?: Array<string>;
}

/**
    * @export
    * @enum {string}
    */
// Enum InteractiveElementElementTypeEnum converted to direct string literals in interface


