/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KeywordRule
 */
export interface KeywordRule {
    /**
     * 
     * @type {string}
     * @memberof KeywordRule
     */
    'category'?: string;
    /**
     * 
     * @type {number}
     * @memberof KeywordRule
     */
    'contextChars'?: number;
    /**
     * 
     * @type {string}
     * @memberof KeywordRule
     */
    'createdAt'?: string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof KeywordRule
     */
    'id'?: UUID;
    /**
     * 
     * @type {boolean}
     * @memberof KeywordRule
     */
    'isCaseSensitive'?: boolean;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof KeywordRule
     */
    'keywordSetId'?: UUID;
    /**
     * 
     * @type {string}
     * @memberof KeywordRule
     */
    'pattern': string;
    /**
     * 
     * @type {string}
     * @memberof KeywordRule
     */
    'ruleType': 'string' | 'regex';
    /**
     * 
     * @type {string}
     * @memberof KeywordRule
     */
    'updatedAt'?: string;
}

/**
    * @export
    * @enum {string}
    */
// Enum KeywordRuleRuleTypeEnum converted to direct string literals in interface


