/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KeywordExtractionRequestItem
 */
export interface KeywordExtractionRequestItem {
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof KeywordExtractionRequestItem
     */
    'dnsPersonaId'?: UUID;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof KeywordExtractionRequestItem
     */
    'httpPersonaId'?: UUID;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof KeywordExtractionRequestItem
     */
    'keywordSetId': UUID;
    /**
     * 
     * @type {string}
     * @memberof KeywordExtractionRequestItem
     */
    'url': string;
}

