/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { KeywordRule } from './keyword-rule';

/**
 * 
 * @export
 * @interface KeywordSet
 */
export interface KeywordSet {
    /**
     * 
     * @type {string}
     * @memberof KeywordSet
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof KeywordSet
     */
    'description'?: string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof KeywordSet
     */
    'id'?: UUID;
    /**
     * 
     * @type {boolean}
     * @memberof KeywordSet
     */
    'isEnabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof KeywordSet
     */
    'name': string;
    /**
     * 
     * @type {Array<KeywordRule>}
     * @memberof KeywordSet
     */
    'rules'?: Array<KeywordRule>;
    /**
     * 
     * @type {string}
     * @memberof KeywordSet
     */
    'updatedAt'?: string;
}

