/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoggingConfig
 */
export interface LoggingConfig {
    /**
     * 
     * @type {boolean}
     * @memberof LoggingConfig
     */
    'enableFileLogging'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LoggingConfig
     */
    'enableJSONFormat'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LoggingConfig
     */
    'enablePerformanceLogging'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LoggingConfig
     */
    'enableRequestLogging'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoggingConfig
     */
    'level'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoggingConfig
     */
    'logDirectory'?: string;
    /**
     * 
     * @type {number}
     * @memberof LoggingConfig
     */
    'maxAge'?: number;
    /**
     * 
     * @type {number}
     * @memberof LoggingConfig
     */
    'maxBackups'?: number;
    /**
     * 
     * @type {number}
     * @memberof LoggingConfig
     */
    'maxFileSize'?: number;
}

