/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Login credentials
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
    /**
     * CAPTCHA token for bot protection
     * @type {string}
     * @memberof LoginRequest
     */
    'captchaToken'?: string;
    /**
     * User email address
     * @type {string}
     * @memberof LoginRequest
     */
    'email': string;
    /**
     * User password (minimum 6 characters)
     * @type {string}
     * @memberof LoginRequest
     */
    'password': string;
    /**
     * Whether to remember the user session
     * @type {boolean}
     * @memberof LoginRequest
     */
    'rememberMe'?: boolean;
}

