/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MFAChallenge
 */
export interface MFAChallenge {
    /**
     * 
     * @type {number}
     * @memberof MFAChallenge
     */
    'attempts'?: number;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof MFAChallenge
     */
    'challengeId'?: UUID;
    /**
     * 
     * @type {string}
     * @memberof MFAChallenge
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof MFAChallenge
     */
    'expiresAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof MFAChallenge
     */
    'maxAttempts'?: number;
    /**
     * 
     * @type {string}
     * @memberof MFAChallenge
     */
    'method'?: 'totp' | 'sms' | 'email' | 'backup';
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof MFAChallenge
     */
    'userId'?: UUID;
}

/**
    * @export
    * @enum {string}
    */
// Enum MFAChallengeMethodEnum converted to direct string literals in interface


