/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * General Campaign Settings
 * @export
 * @interface ModelsBulkCampaignOperationConfigGeneralSettings
 */
export interface ModelsBulkCampaignOperationConfigGeneralSettings {
    /**
     * 
     * @type {string}
     * @memberof ModelsBulkCampaignOperationConfigGeneralSettings
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsBulkCampaignOperationConfigGeneralSettings
     */
    'proxyPoolId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsBulkCampaignOperationConfigGeneralSettings
     */
    'proxySelectionStrategy'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsBulkCampaignOperationConfigGeneralSettings
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsBulkCampaignOperationConfigGeneralSettings
     */
    'variableLength'?: number;
}

