/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsBulkOperationMetadata } from './models-bulk-operation-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsBulkOperationResults } from './models-bulk-operation-results';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsOperationProgress } from './models-operation-progress';

/**
 * 
 * @export
 * @interface ModelsBulkOperationStatus
 */
export interface ModelsBulkOperationStatus {
    /**
     * 
     * @type {number}
     * @memberof ModelsBulkOperationStatus
     */
    'durationMs'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsBulkOperationStatus
     */
    'endTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsBulkOperationStatus
     */
    'error'?: string;
    /**
     * 
     * @type {ModelsBulkOperationMetadata}
     * @memberof ModelsBulkOperationStatus
     */
    'metadata'?: ModelsBulkOperationMetadata;
    /**
     * 
     * @type {string}
     * @memberof ModelsBulkOperationStatus
     */
    'operationId'?: string;
    /**
     * 
     * @type {ModelsOperationProgress}
     * @memberof ModelsBulkOperationStatus
     */
    'progress'?: ModelsOperationProgress;
    /**
     * 
     * @type {ModelsBulkOperationResults}
     * @memberof ModelsBulkOperationStatus
     */
    'results'?: ModelsBulkOperationResults;
    /**
     * 
     * @type {string}
     * @memberof ModelsBulkOperationStatus
     */
    'startTime'?: string;
    /**
     * \"queued\", \"running\", \"completed\", \"failed\", \"cancelled\"
     * @type {string}
     * @memberof ModelsBulkOperationStatus
     */
    'status'?: string;
    /**
     * \"domain_generation\", \"dns_validation\", \"http_validation\", \"analytics\"
     * @type {string}
     * @memberof ModelsBulkOperationStatus
     */
    'type'?: string;
}

