/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsProxy } from './models-proxy';

/**
 * 
 * @export
 * @interface ModelsProxyPool
 */
export interface ModelsProxyPool {
    /**
     * 
     * @type {string}
     * @memberof ModelsProxyPool
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsProxyPool
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsProxyPool
     */
    'healthCheckEnabled'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ModelsProxyPool
     */
    'healthCheckIntervalSeconds'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsProxyPool
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsProxyPool
     */
    'isEnabled'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ModelsProxyPool
     */
    'maxRetries'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsProxyPool
     */
    'name': string;
    /**
     * round_robin, random, weighted, failover
     * @type {string}
     * @memberof ModelsProxyPool
     */
    'poolStrategy'?: string;
    /**
     * Computed fields (not stored in DB)
     * @type {Array<ModelsProxy>}
     * @memberof ModelsProxyPool
     */
    'proxies'?: Array<ModelsProxy>;
    /**
     * 
     * @type {number}
     * @memberof ModelsProxyPool
     */
    'timeoutSeconds'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsProxyPool
     */
    'updatedAt'?: string;
}

