/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsKeywordRuleTypeEnum } from './models-keyword-rule-type-enum';

/**
 * 
 * @export
 * @interface ModelsKeywordRule
 */
export interface ModelsKeywordRule {
    /**
     * 
     * @type {string}
     * @memberof ModelsKeywordRule
     */
    'category'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsKeywordRule
     */
    'contextChars'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsKeywordRule
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsKeywordRule
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsKeywordRule
     */
    'isCaseSensitive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsKeywordRule
     */
    'keywordSetId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsKeywordRule
     */
    'pattern': string;
    /**
     * 
     * @type {ModelsKeywordRuleTypeEnum}
     * @memberof ModelsKeywordRule
     */
    'ruleType': ModelsKeywordRuleTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ModelsKeywordRule
     */
    'updatedAt'?: string;
}



