/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsPhasePerformance } from './models-phase-performance';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsResourceUtilizationMetrics } from './models-resource-utilization-metrics';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsTLDPerformance } from './models-tldperformance';

/**
 * 
 * @export
 * @interface ModelsAggregatedAnalytics
 */
export interface ModelsAggregatedAnalytics {
    /**
     * 
     * @type {number}
     * @memberof ModelsAggregatedAnalytics
     */
    'overallSuccessRate'?: number;
    /**
     * 
     * @type {ModelsResourceUtilizationMetrics}
     * @memberof ModelsAggregatedAnalytics
     */
    'resourceUtilization'?: ModelsResourceUtilizationMetrics;
    /**
     * 
     * @type {Array<ModelsPhasePerformance>}
     * @memberof ModelsAggregatedAnalytics
     */
    'topPerformingPhases'?: Array<ModelsPhasePerformance>;
    /**
     * 
     * @type {Array<ModelsTLDPerformance>}
     * @memberof ModelsAggregatedAnalytics
     */
    'topPerformingTlds'?: Array<ModelsTLDPerformance>;
    /**
     * 
     * @type {number}
     * @memberof ModelsAggregatedAnalytics
     */
    'totalCampaigns'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsAggregatedAnalytics
     */
    'totalDomains'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsAggregatedAnalytics
     */
    'totalLeads'?: number;
}

