/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsTimeRangeFilter
 */
export interface ModelsTimeRangeFilter {
    /**
     * ISO 8601
     * @type {string}
     * @memberof ModelsTimeRangeFilter
     */
    'endTime': string;
    /**
     * ISO 8601
     * @type {string}
     * @memberof ModelsTimeRangeFilter
     */
    'startTime': string;
    /**
     * \"UTC\", \"America/New_York\", etc.
     * @type {string}
     * @memberof ModelsTimeRangeFilter
     */
    'timezone'?: string;
}

