/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatternOffsetRequest
 */
export interface PatternOffsetRequest {
  /**
   * 
   * @memberof PatternOffsetRequest
   */
  'patternType': 
      'prefix' | 'suffix' | 'both'
;
  /**
   * Optional prefix-side variable length when patternType is prefix or both
   * @memberof PatternOffsetRequest
   */
  'prefixVariableLength'?: 
        
          
          number
    ;
  /**
   * Optional suffix-side variable length when patternType is suffix or both
   * @memberof PatternOffsetRequest
   */
  'suffixVariableLength'?: 
        
          
          number
    ;
  /**
   * Legacy combined length retained for backwards compatibility (prefix+suffix)
   * @memberof PatternOffsetRequest
   */
  'variableLength'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof PatternOffsetRequest
   */
  'characterSet': 
        
          
          string
    ;
  /**
   * 
   * @memberof PatternOffsetRequest
   */
  'constantString'?: 
        
          
          string
    ;
  /**
   * Single TLD including dot, e.g. .com or without dot
   * @memberof PatternOffsetRequest
   */
  'tld'?: 
        
          
          string
    ;
}


