/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Time series performance metric for export
 * @export
 * @interface PerformanceMetricRecord
 */
export interface PerformanceMetricRecord {
    /**
     * 
     * @type {string}
     * @memberof PerformanceMetricRecord
     */
    'metricKey': string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceMetricRecord
     */
    'timestamp': string;
    /**
     * 
     * @type {number}
     * @memberof PerformanceMetricRecord
     */
    'value': number;
    /**
     * 
     * @type {string}
     * @memberof PerformanceMetricRecord
     */
    'window'?: PerformanceMetricRecordWindowEnum;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof PerformanceMetricRecord
     */
    'breakdown'?: { [key: string]: number; };
}

/**
    * @export
    * @enum {string}
    */
export enum PerformanceMetricRecordWindowEnum {
    raw = 'raw',
    _1m = '1m',
    _5m = '5m',
    _1h = '1h',
    _1d = '1d'
}


