/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MetricComparison } from './metric-comparison';
// May contain unused imports in some cases
// @ts-ignore
import type { RegressionAnalysis } from './regression-analysis';
// May contain unused imports in some cases
// @ts-ignore
import type { SignificantChange } from './significant-change';
// May contain unused imports in some cases
// @ts-ignore
import type { StatisticalSignificanceData } from './statistical-significance-data';

/**
 * 
 * @export
 * @interface PerformanceComparison
 */
export interface PerformanceComparison {
    /**
     * 
     * @type {Array<MetricComparison>}
     * @memberof PerformanceComparison
     */
    'metricComparisons'?: Array<MetricComparison>;
    /**
     * 
     * @type {number}
     * @memberof PerformanceComparison
     */
    'overallImprovement'?: number;
    /**
     * 
     * @type {RegressionAnalysis}
     * @memberof PerformanceComparison
     */
    'regressionAnalysis'?: RegressionAnalysis;
    /**
     * 
     * @type {Array<SignificantChange>}
     * @memberof PerformanceComparison
     */
    'significantChanges'?: Array<SignificantChange>;
    /**
     * 
     * @type {StatisticalSignificanceData}
     * @memberof PerformanceComparison
     */
    'statisticalSignificance'?: StatisticalSignificanceData;
}

