/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConfigGetStealth200Response } from './config-get-stealth200-response';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonaConfigHttpCookieHandling } from './persona-config-http-cookie-handling';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonaConfigHttpTlsClientHello } from './persona-config-http-tls-client-hello';

/**
 * HTTP persona configuration details
 * @export
 * @interface PersonaConfigHttp
 */
export interface PersonaConfigHttp {
    /**
     * 
     * @type {string}
     * @memberof PersonaConfigHttp
     */
    'personaType': PersonaConfigHttpPersonaTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PersonaConfigHttp
     */
    'userAgent': string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PersonaConfigHttp
     */
    'headers'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof PersonaConfigHttp
     */
    'headerOrder'?: Array<string>;
    /**
     * 
     * @type {PersonaConfigHttpTlsClientHello}
     * @memberof PersonaConfigHttp
     */
    'tlsClientHello'?: PersonaConfigHttpTlsClientHello;
    /**
     * 
     * @type {ConfigGetStealth200Response}
     * @memberof PersonaConfigHttp
     */
    'http2Settings'?: ConfigGetStealth200Response;
    /**
     * 
     * @type {PersonaConfigHttpCookieHandling}
     * @memberof PersonaConfigHttp
     */
    'cookieHandling'?: PersonaConfigHttpCookieHandling;
    /**
     * 
     * @type {number}
     * @memberof PersonaConfigHttp
     */
    'requestTimeoutSeconds'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PersonaConfigHttp
     */
    'followRedirects'?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof PersonaConfigHttp
     */
    'allowedStatusCodes'?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof PersonaConfigHttp
     */
    'rateLimitDps'?: number;
    /**
     * 
     * @type {number}
     * @memberof PersonaConfigHttp
     */
    'rateLimitBurst'?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonaConfigHttp
     */
    'notes'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum PersonaConfigHttpPersonaTypeEnum {
    http = 'http'
}


