/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PersonaConfigDetails } from './persona-config-details';

/**
 * 
 * @export
 * @interface PersonaUpdateRequest
 */
export interface PersonaUpdateRequest {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof PersonaUpdateRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonaUpdateRequest
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PersonaUpdateRequest
     */
    'isEnabled'?: boolean;
    /**
     * 
     * @type {PersonaConfigDetails}
     * @memberof PersonaUpdateRequest
     */
    'configDetails'?: PersonaConfigDetails;
}

