/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonaResponse
 */
export interface PersonaResponse {
    /**
     * 
     * @type {object}
     * @memberof PersonaResponse
     */
    'configDetails'?: object;
    /**
     * 
     * @type {string}
     * @memberof PersonaResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonaResponse
     */
    'description'?: string;
    /**
     * Unique identifier
     * @type {string}
     * @memberof PersonaResponse
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PersonaResponse
     */
    'isEnabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PersonaResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonaResponse
     */
    'personaType'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonaResponse
     */
    'updatedAt'?: string;
}

