/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PhaseStatusResponseProgress
 */
export interface PhaseStatusResponseProgress {
  /**
   * 
   * @memberof PhaseStatusResponseProgress
   */
  'totalItems'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseStatusResponseProgress
   */
  'processedItems'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseStatusResponseProgress
   */
  'successfulItems'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseStatusResponseProgress
   */
  'failedItems'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseStatusResponseProgress
   */
  'percentComplete'?: 
        
          
          number
    ;
}


