/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PhaseConfigurationRequestPersonaIds } from './phase-configuration-request-persona-ids';

/**
 * 
 * @export
 * @interface PhaseConfigurationRequest
 */
export interface PhaseConfigurationRequest {
    /**
     * Phase-specific configuration
     * @type {{ [key: string]: any; }}
     * @memberof PhaseConfigurationRequest
     */
    'configuration': { [key: string]: any; };
    /**
     * 
     * @type {PhaseConfigurationRequestPersonaIds}
     * @memberof PhaseConfigurationRequest
     */
    'personaIds'?: PhaseConfigurationRequestPersonaIds;
    /**
     * 
     * @type {string}
     * @memberof PhaseConfigurationRequest
     */
    'proxyPoolId'?: string;
    /**
     * Keyword sets for extraction phase
     * @type {Array<string>}
     * @memberof PhaseConfigurationRequest
     */
    'keywordSetIds'?: Array<string>;
}

