/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExecutionStatusEnum } from './execution-status-enum';

/**
 * 
 * @export
 * @interface PhaseExecution
 */
export interface PhaseExecution {
  /**
   * 
   * @memberof PhaseExecution
   */
  'id': 
        
          
          string
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'campaignId': 
        
          
          string
    ;
  /**
   * Phase identifier
   * @memberof PhaseExecution
   */
  'phaseType': 
      'discovery' | 'validation' | 'extraction' | 'analysis'
;
  /**
   * 
   * @memberof PhaseExecution
   */
  'status': 
        
          
          ExecutionStatusEnum
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'startedAt'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'completedAt'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'pausedAt'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'failedAt'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'progressPercentage'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'totalItems'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'processedItems'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'successfulItems'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'failedItems'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'configuration'?: 
        Record<string, unknown>
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'errorDetails'?: 
        Record<string, unknown>
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'metrics'?: 
        Record<string, unknown>
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'createdAt': 
        
          
          string
    ;
  /**
   * 
   * @memberof PhaseExecution
   */
  'updatedAt': 
        
          
          string
    ;
}


