/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PhaseProgressSummary
 */
export interface PhaseProgressSummary {
  /**
   * 
   * @memberof PhaseProgressSummary
   */
  'status': 
      'not_started' | 'configured' | 'running' | 'paused' | 'completed' | 'failed'
;
  /**
   * 
   * @memberof PhaseProgressSummary
   */
  'percentComplete': 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseProgressSummary
   */
  'itemsProcessed': 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseProgressSummary
   */
  'itemsTotal': 
        
          
          number
    ;
  /**
   * 
   * @memberof PhaseProgressSummary
   */
  'startedAt'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof PhaseProgressSummary
   */
  'completedAt'?: 
        
          
          string
    ;
  /**
   * Human readable duration
   * @memberof PhaseProgressSummary
   */
  'duration'?: 
        
          
          string
    ;
}


