/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PreparationRecommendation
 */
export interface PreparationRecommendation {
    /**
     * 
     * @type {string}
     * @memberof PreparationRecommendation
     */
    'actionDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof PreparationRecommendation
     */
    'expectedBenefit'?: string;
    /**
     * 
     * @type {string}
     * @memberof PreparationRecommendation
     */
    'implementationRisk'?: 'low' | 'medium' | 'high';
    /**
     * 
     * @type {string}
     * @memberof PreparationRecommendation
     */
    'priority'?: 'low' | 'medium' | 'high' | 'critical';
    /**
     * 
     * @type {string}
     * @memberof PreparationRecommendation
     */
    'recommendationType'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PreparationRecommendation
     */
    'resourceRequirements'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PreparationRecommendation
     */
    'targetScenarios'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PreparationRecommendation
     */
    'timeFrame'?: string;
}

/**
    * @export
    * @enum {string}
    */
// Enum PreparationRecommendationImplementationRiskEnum converted to direct string literals in interface
/**
    * @export
    * @enum {string}
    */
// Enum PreparationRecommendationPriorityEnum converted to direct string literals in interface


