/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProbabilisticForecastResponseModelInfoArbitrationScores } from './probabilistic-forecast-response-model-info-arbitration-scores';

/**
 * 
 * @export
 * @interface ProbabilisticForecastResponseModelInfo
 */
export interface ProbabilisticForecastResponseModelInfo {
  /**
   * 
   * @memberof ProbabilisticForecastResponseModelInfo
   */
  'selectedModel'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof ProbabilisticForecastResponseModelInfo
   */
  'arbitrationScores'?: 
        
          
          ProbabilisticForecastResponseModelInfoArbitrationScores
    ;
}


