/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FlexibleValue } from './flexible-value';

/**
 * Lightweight proxy reference entry for inclusion inside a pool listing.
 * @export
 * @interface ProxyPoolProxyRef
 */
export interface ProxyPoolProxyRef {
    /**
     * 
     * @type {string}
     * @memberof ProxyPoolProxyRef
     */
    'proxyId': string;
    /**
     * 
     * @type {string}
     * @memberof ProxyPoolProxyRef
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof ProxyPoolProxyRef
     */
    'protocol': string;
    /**
     * 
     * @type {boolean}
     * @memberof ProxyPoolProxyRef
     */
    'isHealthy': boolean;
    /**
     * 
     * @type {string}
     * @memberof ProxyPoolProxyRef
     */
    'lastChecked'?: string;
    /**
     * 
     * @type {{ [key: string]: FlexibleValue; }}
     * @memberof ProxyPoolProxyRef
     */
    'metadata'?: { [key: string]: FlexibleValue; };
}

