/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProxyTestResponse
 */
export interface ProxyTestResponse {
    /**
     * 
     * @type {string}
     * @memberof ProxyTestResponse
     */
    'proxyId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProxyTestResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProxyTestResponse
     */
    'statusCode'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProxyTestResponse
     */
    'responseTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProxyTestResponse
     */
    'error'?: string;
}

