/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Proxy manager configuration
 * @export
 * @interface ProxyManagerConfigJSON
 */
export interface ProxyManagerConfigJSON {
  /**
   * Proxy rotation / selection strategy
   * @memberof ProxyManagerConfigJSON
   */
  'strategy': 
      'round_robin' | 'random' | 'geo' | 'sticky'
;
  /**
   * Interval between proxy rotations
   * @memberof ProxyManagerConfigJSON
   */
  'rotationIntervalSeconds': 
        
          
          number
    ;
  /**
   * Maximum size of proxy pool
   * @memberof ProxyManagerConfigJSON
   */
  'poolSize'?: 
        
          
          number
    ;
  /**
   * Failure threshold before proxy eviction
   * @memberof ProxyManagerConfigJSON
   */
  'failThreshold'?: 
        
          
          number
    ;
  /**
   * Fallback proxy endpoint
   * @memberof ProxyManagerConfigJSON
   */
  'fallbackProxy'?: 
        
          
          string
    ;
  /**
   * Additional proxy manager options
   * @memberof ProxyManagerConfigJSON
   */
  'extras'?: 
        Record<string, unknown>
    ;
}


