/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProxyTestResponse
 */
export interface ProxyTestResponse {
    /**
     * 
     * @type {string}
     * @memberof ProxyTestResponse
     */
    'error'?: string;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof ProxyTestResponse
     */
    'proxyId'?: UUID;
    /**
     * 
     * @type {number}
     * @memberof ProxyTestResponse
     */
    'responseTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProxyTestResponse
     */
    'statusCode'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProxyTestResponse
     */
    'success'?: boolean;
}

