/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Rate limiter configuration
 * @export
 * @interface RateLimiterConfig
 */
export interface RateLimiterConfig {
    [key: string]: any;

    /**
     * Enable request rate limiting
     * @type {boolean}
     * @memberof RateLimiterConfig
     */
    'enabled': boolean;
    /**
     * Rate limiting algorithm
     * @type {string}
     * @memberof RateLimiterConfig
     */
    'strategy': RateLimiterConfigStrategyEnum;
    /**
     * Window size for fixed/sliding strategies
     * @type {number}
     * @memberof RateLimiterConfig
     */
    'windowSeconds': number;
    /**
     * Maximum requests per window
     * @type {number}
     * @memberof RateLimiterConfig
     */
    'maxRequests': number;
    /**
     * Additional burst capacity
     * @type {number}
     * @memberof RateLimiterConfig
     */
    'burst'?: number;
    /**
     * Maximum concurrent in-flight requests
     * @type {number}
     * @memberof RateLimiterConfig
     */
    'concurrentLimit'?: number;
    /**
     * Temporary ban duration when threshold exceeded
     * @type {number}
     * @memberof RateLimiterConfig
     */
    'banDurationSeconds'?: number;
    /**
     * Use X-Forwarded-For for client identity
     * @type {boolean}
     * @memberof RateLimiterConfig
     */
    'respectForwardedFor'?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum RateLimiterConfigStrategyEnum {
    fixed_window = 'fixed_window',
    sliding_window = 'sliding_window',
    token_bucket = 'token_bucket'
}


