/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Validation result TTLs
 * @export
 * @interface RedisConfigValidationTTL
 */
export interface RedisConfigValidationTTL {
    /**
     * 
     * @type {string}
     * @memberof RedisConfigValidationTTL
     */
    'configFingerprintTTL'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedisConfigValidationTTL
     */
    'dnsValidationTTL'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedisConfigValidationTTL
     */
    'httpValidationTTL'?: string;
}

