/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RequiredResources
 */
export interface RequiredResources {
    /**
     * 
     * @type {number}
     * @memberof RequiredResources
     */
    'cpuCores'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequiredResources
     */
    'memoryMB'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequiredResources
     */
    'networkMbps'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequiredResources
     */
    'personas'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequiredResources
     */
    'proxies'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequiredResources
     */
    'storageMB'?: number;
}

