/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResourceUsageHistoryPoint
 */
export interface ResourceUsageHistoryPoint {
    /**
     * 
     * @type {number}
     * @memberof ResourceUsageHistoryPoint
     */
    'cost'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceUsageHistoryPoint
     */
    'efficiency'?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceUsageHistoryPoint
     */
    'timestamp'?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceUsageHistoryPoint
     */
    'usage'?: number;
}

