/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResourceUtilizationMetrics
 */
export interface ResourceUtilizationMetrics {
    /**
     * 
     * @type {number}
     * @memberof ResourceUtilizationMetrics
     */
    'cpuUsage'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceUtilizationMetrics
     */
    'databaseQueries'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceUtilizationMetrics
     */
    'memoryUsage'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceUtilizationMetrics
     */
    'networkIO'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceUtilizationMetrics
     */
    'proxyRequests'?: number;
}

