/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CostOptimizationStrategy } from './cost-optimization-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { ImplementedOptimization } from './implemented-optimization';

/**
 * 
 * @export
 * @interface ResourceCostOptimization
 */
export interface ResourceCostOptimization {
    /**
     * 
     * @type {number}
     * @memberof ResourceCostOptimization
     */
    'currentMonthlySpend'?: number;
    /**
     * 
     * @type {Array<ImplementedOptimization>}
     * @memberof ResourceCostOptimization
     */
    'implementedOptimizations'?: Array<ImplementedOptimization>;
    /**
     * 
     * @type {Array<CostOptimizationStrategy>}
     * @memberof ResourceCostOptimization
     */
    'optimizationStrategies'?: Array<CostOptimizationStrategy>;
    /**
     * 
     * @type {number}
     * @memberof ResourceCostOptimization
     */
    'potentialMonthlySavings'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceCostOptimization
     */
    'savingsToDate'?: number;
}

