/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResourceChange
 */
export interface ResourceChange {
    /**
     * 
     * @type {string}
     * @memberof ResourceChange
     */
    'changeType'?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceChange
     */
    'currentValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceChange
     */
    'expectedImpact'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceChange
     */
    'justification'?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceChange
     */
    'recommendedValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceChange
     */
    'resourceType'?: string;
}

