/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResourceUtilizationMetric
 */
export interface ResourceUtilizationMetric {
    /**
     * 
     * @type {boolean}
     * @memberof ResourceUtilizationMetric
     */
    'bottleneckDetected'?: boolean;
    /**
     * Unique identifier
     * @type {string}
     * @memberof ResourceUtilizationMetric
     */
    'campaignId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceUtilizationMetric
     */
    'campaignType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceUtilizationMetric
     */
    'component'?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceUtilizationMetric
     */
    'currentUsage'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceUtilizationMetric
     */
    'efficiencyScore'?: number;
    /**
     * Unique identifier
     * @type {string}
     * @memberof ResourceUtilizationMetric
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceUtilizationMetric
     */
    'maxCapacity'?: number;
    /**
     * 
     * @type {object}
     * @memberof ResourceUtilizationMetric
     */
    'optimizationApplied'?: object;
    /**
     * 
     * @type {string}
     * @memberof ResourceUtilizationMetric
     */
    'recordedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceUtilizationMetric
     */
    'resourceType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceUtilizationMetric
     */
    'serviceName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceUtilizationMetric
     */
    'utilizationPct'?: number;
}

