/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResourceBaselineMetrics
 */
export interface ResourceBaselineMetrics {
    /**
     * 
     * @type {number}
     * @memberof ResourceBaselineMetrics
     */
    'averageCPUUsage'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceBaselineMetrics
     */
    'averageMemoryUsage'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceBaselineMetrics
     */
    'averageNetworkUsage'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceBaselineMetrics
     */
    'averageStorageUsage'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceBaselineMetrics
     */
    'costEfficiencyScore'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceBaselineMetrics
     */
    'resourceEfficiencyScore'?: number;
}

