/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResponsiveSettings
 */
export interface ResponsiveSettings {
    /**
     * 
     * @type {number}
     * @memberof ResponsiveSettings
     */
    'breakpointLarge'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsiveSettings
     */
    'breakpointMedium'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsiveSettings
     */
    'breakpointSmall'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsiveSettings
     */
    'flexibleLayout'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsiveSettings
     */
    'mobileOptimized'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsiveSettings
     */
    'responsiveCharts'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsiveSettings
     */
    'tabletOptimized'?: boolean;
}

