/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RuleQueryFilter
 */
export interface RuleQueryFilter {
    /**
     * 
     * @type {string}
     * @memberof RuleQueryFilter
     */
    'category'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RuleQueryFilter
     */
    'isCaseSensitive'?: boolean;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof RuleQueryFilter
     */
    'keywordSetId'?: UUID;
    /**
     * 
     * @type {number}
     * @memberof RuleQueryFilter
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof RuleQueryFilter
     */
    'offset'?: number;
    /**
     * 
     * @type {string}
     * @memberof RuleQueryFilter
     */
    'patternSearch'?: string;
    /**
     * 
     * @type {string}
     * @memberof RuleQueryFilter
     */
    'ruleType'?: string;
}

