/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScalingRecommendation
 */
export interface ScalingRecommendation {
    /**
     * 
     * @type {string}
     * @memberof ScalingRecommendation
     */
    'component'?: string;
    /**
     * 
     * @type {number}
     * @memberof ScalingRecommendation
     */
    'currentCapacity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ScalingRecommendation
     */
    'estimatedCost'?: number;
    /**
     * 
     * @type {string}
     * @memberof ScalingRecommendation
     */
    'expectedBenefit'?: string;
    /**
     * 
     * @type {number}
     * @memberof ScalingRecommendation
     */
    'recommendedScale'?: number;
    /**
     * 
     * @type {string}
     * @memberof ScalingRecommendation
     */
    'timeFrame'?: string;
}

