/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SchemaStats
 */
export interface SchemaStats {
    /**
     * 
     * @type {string}
     * @memberof SchemaStats
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof SchemaStats
     */
    'tableCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof SchemaStats
     */
    'totalRows'?: number;
    /**
     * 
     * @type {string}
     * @memberof SchemaStats
     */
    'totalSize'?: string;
}

