/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SeasonalPattern
 */
export interface SeasonalPattern {
    /**
     * 
     * @type {number}
     * @memberof SeasonalPattern
     */
    'amplitudeVariation'?: number;
    /**
     * 
     * @type {string}
     * @memberof SeasonalPattern
     */
    'nextPredictedPeak'?: string;
    /**
     * 
     * @type {string}
     * @memberof SeasonalPattern
     */
    'nextPredictedTrough'?: string;
    /**
     * 
     * @type {number}
     * @memberof SeasonalPattern
     */
    'patternStrength'?: number;
    /**
     * 
     * @type {string}
     * @memberof SeasonalPattern
     */
    'patternType'?: string;
    /**
     * 
     * @type {string}
     * @memberof SeasonalPattern
     */
    'peakTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof SeasonalPattern
     */
    'troughTime'?: string;
}

