/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SecurityComplianceData
 */
export interface SecurityComplianceData {
    /**
     * 
     * @type {number}
     * @memberof SecurityComplianceData
     */
    'accessControlCompliance'?: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityComplianceData
     */
    'auditTrailCompliance'?: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityComplianceData
     */
    'dataRetentionCompliance'?: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityComplianceData
     */
    'encryptionCompliance'?: number;
}

