/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Using OpenAPI compatible types instead of branded types

/**
 *
 * @export
 * @interface ServicesDomainGenerationParams
 */
export interface ServicesDomainGenerationParams {
    /**
     *
     * @type {string}
     * @memberof ServicesDomainGenerationParams
     */
    'characterSet': string;
    /**
     *
     * @type {string}
     * @memberof ServicesDomainGenerationParams
     */
    'constantString': string;
    /**
     *
     * @type {number}
     * @memberof ServicesDomainGenerationParams
     */
    'numDomainsToGenerate'?: number;
    /**
     *
     * @type {string}
     * @memberof ServicesDomainGenerationParams
     */
    'patternType': ServicesDomainGenerationParamsPatternTypeEnum;
    /**
     * OpenAPI compatible: Use number for int64 field
     * @type {number}
     * @memberof ServicesDomainGenerationParams
     */
    'totalPossibleCombinations'?: number;
    /**
     * OpenAPI compatible: Use number for int64 field
     * @type {number}
     * @memberof ServicesDomainGenerationParams
     */
    'currentOffset'?: number;
    /**
     *
     * @type {string}
     * @memberof ServicesDomainGenerationParams
     */
    'tld': string;
    /**
     *
     * @type {number}
     * @memberof ServicesDomainGenerationParams
     */
    'variableLength': number;
}

export const ServicesDomainGenerationParamsPatternTypeEnum = {
    Prefix: 'prefix',
    Suffix: 'suffix',
    Both: 'both'
} as const;

export type ServicesDomainGenerationParamsPatternTypeEnum = typeof ServicesDomainGenerationParamsPatternTypeEnum[keyof typeof ServicesDomainGenerationParamsPatternTypeEnum];
