/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Server configuration
 * @export
 * @interface ServerConfig
 */
export interface ServerConfig {
    /**
     * Gin framework mode
     * @type {string}
     * @memberof ServerConfig
     */
    'ginMode'?: ServerConfigGinModeEnum;
    /**
     * Server port
     * @type {string}
     * @memberof ServerConfig
     */
    'port'?: string;
    /**
     * Stream chunk size in bytes
     * @type {number}
     * @memberof ServerConfig
     */
    'streamChunkSize'?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum ServerConfigGinModeEnum {
    Debug = 'debug',
    Release = 'release',
    Test = 'test'
}


