/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServicesUpdateCampaignRequest
 */
export interface ServicesUpdateCampaignRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ServicesUpdateCampaignRequest
     */
    'adHocKeywords'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ServicesUpdateCampaignRequest
     */
    'batchSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof ServicesUpdateCampaignRequest
     */
    'campaignType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesUpdateCampaignRequest
     */
    'characterSet'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesUpdateCampaignRequest
     */
    'constantString'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ServicesUpdateCampaignRequest
     */
    'keywordSetIds'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ServicesUpdateCampaignRequest
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof ServicesUpdateCampaignRequest
     */
    'numDomainsToGenerate'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ServicesUpdateCampaignRequest
     */
    'personaIds'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ServicesUpdateCampaignRequest
     */
    'processingSpeedPerMinute'?: number;
    /**
     * 
     * @type {string}
     * @memberof ServicesUpdateCampaignRequest
     */
    'proxyPoolId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesUpdateCampaignRequest
     */
    'proxySelectionStrategy'?: string;
    /**
     * 
     * @type {number}
     * @memberof ServicesUpdateCampaignRequest
     */
    'retryAttempts'?: number;
    /**
     * 
     * @type {number}
     * @memberof ServicesUpdateCampaignRequest
     */
    'rotationIntervalSeconds'?: number;
    /**
     * 
     * @type {string}
     * @memberof ServicesUpdateCampaignRequest
     */
    'sourceDnsCampaignId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesUpdateCampaignRequest
     */
    'sourceGenerationCampaignId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesUpdateCampaignRequest
     */
    'status'?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ServicesUpdateCampaignRequest
     */
    'targetHttpPorts'?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof ServicesUpdateCampaignRequest
     */
    'tld'?: string;
    /**
     * 
     * @type {number}
     * @memberof ServicesUpdateCampaignRequest
     */
    'variableLength'?: number;
}

