/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SessionSettings
 */
export interface SessionSettings {
    /**
     * 
     * @type {Array<string>}
     * @memberof SessionSettings
     */
    'allowed_origins'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SessionSettings
     */
    'cleanup_interval'?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionSettings
     */
    'cookie_domain'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SessionSettings
     */
    'cookie_http_only'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SessionSettings
     */
    'cookie_max_age'?: number;
    /**
     * Cookie settings
     * @type {string}
     * @memberof SessionSettings
     */
    'cookie_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionSettings
     */
    'cookie_path'?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionSettings
     */
    'cookie_same_site'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SessionSettings
     */
    'cookie_secure'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SessionSettings
     */
    'custom_header_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionSettings
     */
    'custom_header_value'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SessionSettings
     */
    'enable_fingerprinting'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SessionSettings
     */
    'idle_timeout'?: string;
    /**
     * 
     * @type {number}
     * @memberof SessionSettings
     */
    'max_login_attempts'?: number;
    /**
     * 
     * @type {number}
     * @memberof SessionSettings
     */
    'max_session_validations'?: number;
    /**
     * 
     * @type {number}
     * @memberof SessionSettings
     */
    'max_sessions_per_user'?: number;
    /**
     * Rate limiting
     * @type {boolean}
     * @memberof SessionSettings
     */
    'rate_limit_enabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SessionSettings
     */
    'rate_limit_window'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SessionSettings
     */
    'require_custom_header'?: boolean;
    /**
     * Security settings
     * @type {boolean}
     * @memberof SessionSettings
     */
    'require_ip_match'?: boolean;
    /**
     * CSRF Protection (without tokens)
     * @type {boolean}
     * @memberof SessionSettings
     */
    'require_origin_validation'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SessionSettings
     */
    'require_ua_match'?: boolean;
    /**
     * Session duration and timeouts
     * @type {string}
     * @memberof SessionSettings
     */
    'session_duration'?: string;
    /**
     * 
     * @type {number}
     * @memberof SessionSettings
     */
    'session_id_length'?: number;
}

