/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SseEventsStats200ResponseAllOfData
 */
export interface SseEventsStats200ResponseAllOfData {
    /**
     * Number of active SSE connections
     * @type {number}
     * @memberof SseEventsStats200ResponseAllOfData
     */
    'activeConnections'?: number;
    /**
     * Total events sent since server start
     * @type {number}
     * @memberof SseEventsStats200ResponseAllOfData
     */
    'totalEventsSent'?: number;
    /**
     * Server uptime
     * @type {string}
     * @memberof SseEventsStats200ResponseAllOfData
     */
    'uptime'?: string;
}

