/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StealthOperationMetrics
 */
export interface StealthOperationMetrics {
    /**
     * 
     * @type {number}
     * @memberof StealthOperationMetrics
     */
    'avgRequestSpacing'?: number;
    /**
     * 
     * @type {number}
     * @memberof StealthOperationMetrics
     */
    'detectionScore'?: number;
    /**
     * 
     * @type {number}
     * @memberof StealthOperationMetrics
     */
    'patternBreaks'?: number;
    /**
     * 
     * @type {number}
     * @memberof StealthOperationMetrics
     */
    'proxyRotations'?: number;
    /**
     * 
     * @type {number}
     * @memberof StealthOperationMetrics
     */
    'randomizationEvents'?: number;
    /**
     * 
     * @type {number}
     * @memberof StealthOperationMetrics
     */
    'temporalJitterEvents'?: number;
    /**
     * 
     * @type {number}
     * @memberof StealthOperationMetrics
     */
    'userAgentRotations'?: number;
}

