/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TimelineEventMetadataValue } from './timeline-event-metadata-value';

/**
 * Unified campaign timeline event for export and progress tracking
 * @export
 * @interface TimelineEvent
 */
export interface TimelineEvent {
  /**
   * 
   * @memberof TimelineEvent
   */
  'timestamp': 
        
          
          string
    ;
  /**
   * 
   * @memberof TimelineEvent
   */
  'phase'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof TimelineEvent
   */
  'type': 
        
          
          string
    ;
  /**
   * 
   * @memberof TimelineEvent
   */
  'description'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof TimelineEvent
   */
  'status'?: 
      'pending' | 'running' | 'completed' | 'failed'
;
  /**
   * 
   * @memberof TimelineEvent
   */
  'progress'?: 
        
          
          number
    ;
  /**
   * 
   * @memberof TimelineEvent
   */
  'metadata'?: 
        Record<string, unknown>
    ;
}


