/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProxyProtocol } from './proxy-protocol';

/**
 * 
 * @export
 * @interface UpdateProxyRequestAPI
 */
export interface UpdateProxyRequestAPI {
  /**
   * 
   * @memberof UpdateProxyRequestAPI
   */
  'name'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof UpdateProxyRequestAPI
   */
  'description'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof UpdateProxyRequestAPI
   */
  'address'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof UpdateProxyRequestAPI
   */
  'protocol'?: 
        
          
          ProxyProtocol
    ;
  /**
   * 
   * @memberof UpdateProxyRequestAPI
   */
  'username'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof UpdateProxyRequestAPI
   */
  'password'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof UpdateProxyRequestAPI
   */
  'countryCode'?: 
        
          
          string
    ;
  /**
   * 
   * @memberof UpdateProxyRequestAPI
   */
  'isEnabled'?: 
        
          
          boolean
    ;
  /**
   * 
   * @memberof UpdateProxyRequestAPI
   */
  'notes'?: 
        
          
          string
    ;
}


