/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValidationStartResponse
 */
export interface ValidationStartResponse {
    /**
     * Unique identifier
     * @type {string}
     * @memberof ValidationStartResponse
     */
    'campaignId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationStartResponse
     */
    'message'?: string;
    /**
     * Unique identifier
     * @type {string}
     * @memberof ValidationStartResponse
     */
    'validationId'?: string;
}

