/* tslint:disable */

import type { UUID } from '../uuid-types';
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValidationOperationResponse
 */
export interface ValidationOperationResponse {
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof ValidationOperationResponse
     */
    'campaignId'?: UUID;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof ValidationOperationResponse
     */
    'jobId'?: UUID;
    /**
     * 
     * @type {string}
     * @memberof ValidationOperationResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ValidationOperationResponse
     */
    'success'?: boolean;
    /**
     * Unique identifier (UUID v4)
     * @type {string}
     * @memberof ValidationOperationResponse
     */
    'validationType'?: UUID;
}

