/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Worker configuration update payload
 * @export
 * @interface WorkerConfigUpdate
 */
export interface WorkerConfigUpdate {
    /**
     * Number of worker threads in the pool
     * @type {number}
     * @memberof WorkerConfigUpdate
     */
    'poolSize'?: number;
    /**
     * Maximum number of jobs in queue
     * @type {number}
     * @memberof WorkerConfigUpdate
     */
    'maxJobs'?: number;
    /**
     * Job execution timeout in seconds
     * @type {number}
     * @memberof WorkerConfigUpdate
     */
    'jobTimeout'?: number;
    /**
     * Worker idle timeout in seconds
     * @type {number}
     * @memberof WorkerConfigUpdate
     */
    'idleTimeout'?: number;
    /**
     * Number of retry attempts for failed jobs
     * @type {number}
     * @memberof WorkerConfigUpdate
     */
    'retryAttempts'?: number;
    /**
     * Delay between retries in milliseconds
     * @type {number}
     * @memberof WorkerConfigUpdate
     */
    'retryDelay'?: number;
    /**
     * Enable worker performance metrics collection
     * @type {boolean}
     * @memberof WorkerConfigUpdate
     */
    'enableMetrics'?: boolean;
    /**
     * Metrics collection interval in seconds
     * @type {number}
     * @memberof WorkerConfigUpdate
     */
    'metricsInterval'?: number;
    /**
     * Worker pool priority level
     * @type {string}
     * @memberof WorkerConfigUpdate
     */
    'priority'?: WorkerConfigUpdatePriorityEnum;
    /**
     * Enable worker health monitoring
     * @type {boolean}
     * @memberof WorkerConfigUpdate
     */
    'enableHealthChecks'?: boolean;
    /**
     * Health check interval in seconds
     * @type {number}
     * @memberof WorkerConfigUpdate
     */
    'healthCheckInterval'?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum WorkerConfigUpdatePriorityEnum {
    low = 'low',
    normal = 'normal',
    high = 'high',
    critical = 'critical'
}


