/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DatabaseOptimizationRecommendation
 */
export interface DatabaseOptimizationRecommendation {
    /**
     * 
     * @type {string}
     * @memberof DatabaseOptimizationRecommendation
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseOptimizationRecommendation
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseOptimizationRecommendation
     */
    'effort'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseOptimizationRecommendation
     */
    'impact'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseOptimizationRecommendation
     */
    'priority'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseOptimizationRecommendation
     */
    'sql'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseOptimizationRecommendation
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseOptimizationRecommendation
     */
    'type'?: string;
}

