/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HTTPKeywordCampaignParams
 */
export interface HTTPKeywordCampaignParams {
    /**
     * 
     * @type {Array<string>}
     * @memberof HTTPKeywordCampaignParams
     */
    'adHocKeywords'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof HTTPKeywordCampaignParams
     */
    'batchSize'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof HTTPKeywordCampaignParams
     */
    'keywordSetIds'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof HTTPKeywordCampaignParams
     */
    'lastProcessedDomainName'?: string;
    /**
     * 
     * @type {object}
     * @memberof HTTPKeywordCampaignParams
     */
    'metadata'?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof HTTPKeywordCampaignParams
     */
    'personaIds': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof HTTPKeywordCampaignParams
     */
    'processingSpeedPerMinute'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof HTTPKeywordCampaignParams
     */
    'proxyIds'?: Array<string>;
    /**
     * Unique identifier
     * @type {string}
     * @memberof HTTPKeywordCampaignParams
     */
    'proxyPoolId'?: string;
    /**
     * 
     * @type {string}
     * @memberof HTTPKeywordCampaignParams
     */
    'proxySelectionStrategy'?: string;
    /**
     * 
     * @type {number}
     * @memberof HTTPKeywordCampaignParams
     */
    'retryAttempts'?: number;
    /**
     * 
     * @type {number}
     * @memberof HTTPKeywordCampaignParams
     */
    'rotationIntervalSeconds'?: number;
    /**
     * Unique identifier
     * @type {string}
     * @memberof HTTPKeywordCampaignParams
     */
    'sourceCampaignId': string;
    /**
     * 
     * @type {string}
     * @memberof HTTPKeywordCampaignParams
     */
    'sourceType': string;
    /**
     * 
     * @type {Array<number>}
     * @memberof HTTPKeywordCampaignParams
     */
    'targetHttpPorts'?: Array<number>;
}

