/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PageInfo
 */
export interface PageInfo {
    /**
     * 
     * @type {number}
     * @memberof PageInfo
     */
    'count'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfo
     */
    'current'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfo
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfo
     */
    'total'?: number;
}

