/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SystemInfo
 */
export interface SystemInfo {
    /**
     * 
     * @type {string}
     * @memberof SystemInfo
     */
    'goVersion'?: string;
    /**
     * 
     * @type {number}
     * @memberof SystemInfo
     */
    'numCPU'?: number;
    /**
     * 
     * @type {number}
     * @memberof SystemInfo
     */
    'numGoroutine'?: number;
}

