/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management.  This API provides comprehensive functionality for: - Entity management (Personas, Proxies, Keyword Sets) - Configuration management - Ad-hoc keyword extraction - V2 Stateful Campaign Management system - Real-time communication via WebSockets - Comprehensive authentication  **Authentication:** The API uses session-based authentication with HTTP-only cookies:  1. **Session-Based Authentication**: Secure HTTP-only cookie-based sessions with session fingerprinting    - Login via `POST /api/v2/auth/login`    - Session cookies: httpOnly, secure, sameSite=strict    - X-Requested-With header required for CSRF protection on state-changing operations    - Automatic session cleanup and concurrent session management  All RESTful API endpoints under `/api/v2` (excluding `GET /ping`) require valid session authentication.  For WebSocket connections, authentication is provided via session cookies (automatically included by browser). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { KeywordSetResponse } from '../models';
/**
 * KeywordsApi - axios parameter creator
 * @export
 */
export const KeywordsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Batch extract keywords
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2ExtractKeywordsPost: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('apiV2ExtractKeywordsPost', 'body', body)
            const localVarPath = `/api/v2/extract/keywords`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionAuth required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Stream extract keywords
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2ExtractKeywordsStreamGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v2/extract/keywords/stream`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List keyword sets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2KeywordsSetsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v2/keywords/sets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create keyword set
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2KeywordsSetsPost: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('apiV2KeywordsSetsPost', 'body', body)
            const localVarPath = `/api/v2/keywords/sets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionAuth required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete keyword set
         * @param {string} setId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2KeywordsSetsSetIdDelete: async (setId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'setId' is not null or undefined
            assertParamExists('apiV2KeywordsSetsSetIdDelete', 'setId', setId)
            const localVarPath = `/api/v2/keywords/sets/{setId}`
                .replace(`{${"setId"}}`, encodeURIComponent(String(setId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get keyword set
         * @param {string} setId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2KeywordsSetsSetIdGet: async (setId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'setId' is not null or undefined
            assertParamExists('apiV2KeywordsSetsSetIdGet', 'setId', setId)
            const localVarPath = `/api/v2/keywords/sets/{setId}`
                .replace(`{${"setId"}}`, encodeURIComponent(String(setId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update keyword set
         * @param {string} setId 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2KeywordsSetsSetIdPut: async (setId: string, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'setId' is not null or undefined
            assertParamExists('apiV2KeywordsSetsSetIdPut', 'setId', setId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('apiV2KeywordsSetsSetIdPut', 'body', body)
            const localVarPath = `/api/v2/keywords/sets/{setId}`
                .replace(`{${"setId"}}`, encodeURIComponent(String(setId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionAuth required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * KeywordsApi - functional programming interface
 * @export
 */
export const KeywordsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = KeywordsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Batch extract keywords
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV2ExtractKeywordsPost(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV2ExtractKeywordsPost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KeywordsApi.apiV2ExtractKeywordsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Stream extract keywords
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV2ExtractKeywordsStreamGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV2ExtractKeywordsStreamGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KeywordsApi.apiV2ExtractKeywordsStreamGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List keyword sets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV2KeywordsSetsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<KeywordSetResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV2KeywordsSetsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KeywordsApi.apiV2KeywordsSetsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create keyword set
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV2KeywordsSetsPost(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KeywordSetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV2KeywordsSetsPost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KeywordsApi.apiV2KeywordsSetsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete keyword set
         * @param {string} setId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV2KeywordsSetsSetIdDelete(setId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV2KeywordsSetsSetIdDelete(setId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KeywordsApi.apiV2KeywordsSetsSetIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get keyword set
         * @param {string} setId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV2KeywordsSetsSetIdGet(setId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KeywordSetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV2KeywordsSetsSetIdGet(setId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KeywordsApi.apiV2KeywordsSetsSetIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update keyword set
         * @param {string} setId 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV2KeywordsSetsSetIdPut(setId: string, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KeywordSetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV2KeywordsSetsSetIdPut(setId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KeywordsApi.apiV2KeywordsSetsSetIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * KeywordsApi - factory interface
 * @export
 */
export const KeywordsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = KeywordsApiFp(configuration)
    return {
        /**
         * 
         * @summary Batch extract keywords
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2ExtractKeywordsPost(body: object, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV2ExtractKeywordsPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Stream extract keywords
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2ExtractKeywordsStreamGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV2ExtractKeywordsStreamGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List keyword sets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2KeywordsSetsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<KeywordSetResponse>> {
            return localVarFp.apiV2KeywordsSetsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create keyword set
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2KeywordsSetsPost(body: object, options?: RawAxiosRequestConfig): AxiosPromise<KeywordSetResponse> {
            return localVarFp.apiV2KeywordsSetsPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete keyword set
         * @param {string} setId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2KeywordsSetsSetIdDelete(setId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV2KeywordsSetsSetIdDelete(setId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get keyword set
         * @param {string} setId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2KeywordsSetsSetIdGet(setId: string, options?: RawAxiosRequestConfig): AxiosPromise<KeywordSetResponse> {
            return localVarFp.apiV2KeywordsSetsSetIdGet(setId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update keyword set
         * @param {string} setId 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2KeywordsSetsSetIdPut(setId: string, body: object, options?: RawAxiosRequestConfig): AxiosPromise<KeywordSetResponse> {
            return localVarFp.apiV2KeywordsSetsSetIdPut(setId, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * KeywordsApi - interface
 * @export
 * @interface KeywordsApi
 */
export interface KeywordsApiInterface {
    /**
     * 
     * @summary Batch extract keywords
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApiInterface
     */
    apiV2ExtractKeywordsPost(body: object, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Stream extract keywords
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApiInterface
     */
    apiV2ExtractKeywordsStreamGet(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary List keyword sets
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApiInterface
     */
    apiV2KeywordsSetsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<KeywordSetResponse>>;

    /**
     * 
     * @summary Create keyword set
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApiInterface
     */
    apiV2KeywordsSetsPost(body: object, options?: RawAxiosRequestConfig): AxiosPromise<KeywordSetResponse>;

    /**
     * 
     * @summary Delete keyword set
     * @param {string} setId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApiInterface
     */
    apiV2KeywordsSetsSetIdDelete(setId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get keyword set
     * @param {string} setId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApiInterface
     */
    apiV2KeywordsSetsSetIdGet(setId: string, options?: RawAxiosRequestConfig): AxiosPromise<KeywordSetResponse>;

    /**
     * 
     * @summary Update keyword set
     * @param {string} setId 
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApiInterface
     */
    apiV2KeywordsSetsSetIdPut(setId: string, body: object, options?: RawAxiosRequestConfig): AxiosPromise<KeywordSetResponse>;

}

/**
 * KeywordsApi - object-oriented interface
 * @export
 * @class KeywordsApi
 * @extends {BaseAPI}
 */
export class KeywordsApi extends BaseAPI implements KeywordsApiInterface {
    /**
     * 
     * @summary Batch extract keywords
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApi
     */
    public apiV2ExtractKeywordsPost(body: object, options?: RawAxiosRequestConfig) {
        return KeywordsApiFp(this.configuration).apiV2ExtractKeywordsPost(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Stream extract keywords
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApi
     */
    public apiV2ExtractKeywordsStreamGet(options?: RawAxiosRequestConfig) {
        return KeywordsApiFp(this.configuration).apiV2ExtractKeywordsStreamGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List keyword sets
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApi
     */
    public apiV2KeywordsSetsGet(options?: RawAxiosRequestConfig) {
        return KeywordsApiFp(this.configuration).apiV2KeywordsSetsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create keyword set
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApi
     */
    public apiV2KeywordsSetsPost(body: object, options?: RawAxiosRequestConfig) {
        return KeywordsApiFp(this.configuration).apiV2KeywordsSetsPost(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete keyword set
     * @param {string} setId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApi
     */
    public apiV2KeywordsSetsSetIdDelete(setId: string, options?: RawAxiosRequestConfig) {
        return KeywordsApiFp(this.configuration).apiV2KeywordsSetsSetIdDelete(setId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get keyword set
     * @param {string} setId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApi
     */
    public apiV2KeywordsSetsSetIdGet(setId: string, options?: RawAxiosRequestConfig) {
        return KeywordsApiFp(this.configuration).apiV2KeywordsSetsSetIdGet(setId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update keyword set
     * @param {string} setId 
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordsApi
     */
    public apiV2KeywordsSetsSetIdPut(setId: string, body: object, options?: RawAxiosRequestConfig) {
        return KeywordsApiFp(this.configuration).apiV2KeywordsSetsSetIdPut(setId, body, options).then((request) => request(this.axios, this.basePath));
    }
}

