/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiLoginSuccessResponse } from '../models';
// @ts-ignore
import type { ApiPasswordChangeResponse } from '../models';
// @ts-ignore
import type { ApiSessionRefreshResponse } from '../models';
// @ts-ignore
import type { ApiStandardErrorResponse } from '../models';
// @ts-ignore
import type { ApiSuccessMessageResponse } from '../models';
// @ts-ignore
import type { GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest } from '../models';
// @ts-ignore
import type { GithubComFntelecomllcStudioBackendInternalModelsLoginRequest } from '../models';
// @ts-ignore
import type { GithubComFntelecomllcStudioBackendInternalModelsUser } from '../models';
/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Change password for the currently authenticated user
         * @summary Change user password
         * @param {GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest} githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest Password change request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword: async (githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest: GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest' is not null or undefined
            assertParamExists('changePassword', 'githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest', githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest)
            const localVarPath = `/auth/change-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get information about the currently authenticated user
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Authenticate user credentials and create session
         * @summary User login
         * @param {GithubComFntelecomllcStudioBackendInternalModelsLoginRequest} githubComFntelecomllcStudioBackendInternalModelsLoginRequest Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser: async (githubComFntelecomllcStudioBackendInternalModelsLoginRequest: GithubComFntelecomllcStudioBackendInternalModelsLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'githubComFntelecomllcStudioBackendInternalModelsLoginRequest' is not null or undefined
            assertParamExists('loginUser', 'githubComFntelecomllcStudioBackendInternalModelsLoginRequest', githubComFntelecomllcStudioBackendInternalModelsLoginRequest)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(githubComFntelecomllcStudioBackendInternalModelsLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Invalidate current user session and clear cookies
         * @summary User logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logoutUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Extend the current session expiry time
         * @summary Refresh user session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshSession: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * Change password for the currently authenticated user
         * @summary Change user password
         * @param {GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest} githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest Password change request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword(githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest: GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiPasswordChangeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword(githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.changePassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get information about the currently authenticated user
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GithubComFntelecomllcStudioBackendInternalModelsUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.getCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Authenticate user credentials and create session
         * @summary User login
         * @param {GithubComFntelecomllcStudioBackendInternalModelsLoginRequest} githubComFntelecomllcStudioBackendInternalModelsLoginRequest Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginUser(githubComFntelecomllcStudioBackendInternalModelsLoginRequest: GithubComFntelecomllcStudioBackendInternalModelsLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiLoginSuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginUser(githubComFntelecomllcStudioBackendInternalModelsLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.loginUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Invalidate current user session and clear cookies
         * @summary User logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logoutUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSuccessMessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logoutUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.logoutUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Extend the current session expiry time
         * @summary Refresh user session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refreshSession(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSessionRefreshResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refreshSession(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.refreshSession']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * Change password for the currently authenticated user
         * @summary Change user password
         * @param {GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest} githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest Password change request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest: GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiPasswordChangeResponse> {
            return localVarFp.changePassword(githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get information about the currently authenticated user
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<GithubComFntelecomllcStudioBackendInternalModelsUser> {
            return localVarFp.getCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * Authenticate user credentials and create session
         * @summary User login
         * @param {GithubComFntelecomllcStudioBackendInternalModelsLoginRequest} githubComFntelecomllcStudioBackendInternalModelsLoginRequest Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser(githubComFntelecomllcStudioBackendInternalModelsLoginRequest: GithubComFntelecomllcStudioBackendInternalModelsLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiLoginSuccessResponse> {
            return localVarFp.loginUser(githubComFntelecomllcStudioBackendInternalModelsLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Invalidate current user session and clear cookies
         * @summary User logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logoutUser(options?: RawAxiosRequestConfig): AxiosPromise<ApiSuccessMessageResponse> {
            return localVarFp.logoutUser(options).then((request) => request(axios, basePath));
        },
        /**
         * Extend the current session expiry time
         * @summary Refresh user session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshSession(options?: RawAxiosRequestConfig): AxiosPromise<ApiSessionRefreshResponse> {
            return localVarFp.refreshSession(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - interface
 * @export
 * @interface AuthenticationApi
 */
export interface AuthenticationApiInterface {
    /**
     * Change password for the currently authenticated user
     * @summary Change user password
     * @param {GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest} githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest Password change request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    changePassword(githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest: GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiPasswordChangeResponse>;

    /**
     * Get information about the currently authenticated user
     * @summary Get current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    getCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<GithubComFntelecomllcStudioBackendInternalModelsUser>;

    /**
     * Authenticate user credentials and create session
     * @summary User login
     * @param {GithubComFntelecomllcStudioBackendInternalModelsLoginRequest} githubComFntelecomllcStudioBackendInternalModelsLoginRequest Login credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    loginUser(githubComFntelecomllcStudioBackendInternalModelsLoginRequest: GithubComFntelecomllcStudioBackendInternalModelsLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiLoginSuccessResponse>;

    /**
     * Invalidate current user session and clear cookies
     * @summary User logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    logoutUser(options?: RawAxiosRequestConfig): AxiosPromise<ApiSuccessMessageResponse>;

    /**
     * Extend the current session expiry time
     * @summary Refresh user session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    refreshSession(options?: RawAxiosRequestConfig): AxiosPromise<ApiSessionRefreshResponse>;

}

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI implements AuthenticationApiInterface {
    /**
     * Change password for the currently authenticated user
     * @summary Change user password
     * @param {GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest} githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest Password change request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public changePassword(githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest: GithubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).changePassword(githubComFntelecomllcStudioBackendInternalModelsChangePasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get information about the currently authenticated user
     * @summary Get current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public getCurrentUser(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).getCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Authenticate user credentials and create session
     * @summary User login
     * @param {GithubComFntelecomllcStudioBackendInternalModelsLoginRequest} githubComFntelecomllcStudioBackendInternalModelsLoginRequest Login credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public loginUser(githubComFntelecomllcStudioBackendInternalModelsLoginRequest: GithubComFntelecomllcStudioBackendInternalModelsLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).loginUser(githubComFntelecomllcStudioBackendInternalModelsLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Invalidate current user session and clear cookies
     * @summary User logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public logoutUser(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).logoutUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Extend the current session expiry time
     * @summary Refresh user session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public refreshSession(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).refreshSession(options).then((request) => request(this.axios, this.basePath));
    }
}

