/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiAPIResponse } from '../models';
// @ts-ignore
import type { ApiBulkResourceStatusResponse } from '../models';
// @ts-ignore
import type { ApiOperationCancellationResponse } from '../models';
// @ts-ignore
import type { BulkValidateDNS200Response } from '../models';
// @ts-ignore
import type { ModelsBulkAnalyticsRequest } from '../models';
// @ts-ignore
import type { ModelsBulkDNSValidationRequest } from '../models';
// @ts-ignore
import type { ModelsBulkDomainGenerationRequest } from '../models';
// @ts-ignore
import type { ModelsBulkHTTPValidationRequest } from '../models';
// @ts-ignore
import type { ModelsBulkOperationStatus } from '../models';
// @ts-ignore
import type { ModelsBulkResourceRequest } from '../models';
/**
 * BulkOperationsApi - axios parameter creator
 * @export
 */
export const BulkOperationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Allocate compute, network, and storage resources for bulk campaign operations with priority scheduling
         * @summary Allocate bulk resources for enterprise operations
         * @param {ModelsBulkResourceRequest} modelsBulkResourceRequest Bulk resource allocation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        allocateBulkResources: async (modelsBulkResourceRequest: ModelsBulkResourceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelsBulkResourceRequest' is not null or undefined
            assertParamExists('allocateBulkResources', 'modelsBulkResourceRequest', modelsBulkResourceRequest)
            const localVarPath = `/campaigns/bulk/resources/allocate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modelsBulkResourceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Perform comprehensive analytics across multiple campaigns with advanced metrics and aggregation
         * @summary Analyze domains in bulk with enterprise intelligence
         * @param {ModelsBulkAnalyticsRequest} modelsBulkAnalyticsRequest Bulk analytics request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkAnalyzeDomains: async (modelsBulkAnalyticsRequest: ModelsBulkAnalyticsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelsBulkAnalyticsRequest' is not null or undefined
            assertParamExists('bulkAnalyzeDomains', 'modelsBulkAnalyticsRequest', modelsBulkAnalyticsRequest)
            const localVarPath = `/campaigns/bulk/analytics/analyze`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modelsBulkAnalyticsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Generate large batches of domains with stealth-aware configuration and resource management
         * @summary Generate domains in bulk using orchestrator
         * @param {ModelsBulkDomainGenerationRequest} modelsBulkDomainGenerationRequest Bulk domain generation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkGenerateDomains: async (modelsBulkDomainGenerationRequest: ModelsBulkDomainGenerationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelsBulkDomainGenerationRequest' is not null or undefined
            assertParamExists('bulkGenerateDomains', 'modelsBulkDomainGenerationRequest', modelsBulkDomainGenerationRequest)
            const localVarPath = `/campaigns/bulk/domains/generate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modelsBulkDomainGenerationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Perform bulk DNS validation with stealth detection avoidance and resource optimization
         * @summary Validate domains using bulk DNS validation with stealth
         * @param {ModelsBulkDNSValidationRequest} modelsBulkDNSValidationRequest Bulk DNS validation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkValidateDNS: async (modelsBulkDNSValidationRequest: ModelsBulkDNSValidationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelsBulkDNSValidationRequest' is not null or undefined
            assertParamExists('bulkValidateDNS', 'modelsBulkDNSValidationRequest', modelsBulkDNSValidationRequest)
            const localVarPath = `/api/v2/campaigns/bulk/domains/validate-dns`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modelsBulkDNSValidationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Perform bulk HTTP validation with keyword extraction, stealth detection avoidance, and resource optimization
         * @summary Validate domains using bulk HTTP validation with stealth
         * @param {ModelsBulkHTTPValidationRequest} modelsBulkHTTPValidationRequest Bulk HTTP validation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkValidateHTTP: async (modelsBulkHTTPValidationRequest: ModelsBulkHTTPValidationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelsBulkHTTPValidationRequest' is not null or undefined
            assertParamExists('bulkValidateHTTP', 'modelsBulkHTTPValidationRequest', modelsBulkHTTPValidationRequest)
            const localVarPath = `/api/v2/campaigns/bulk/domains/validate-http`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modelsBulkHTTPValidationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Cancel running bulk operations and release allocated resources
         * @summary Cancel bulk operations
         * @param {string} operationId Bulk operation ID to cancel
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelBulkOperation: async (operationId: string, body?: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'operationId' is not null or undefined
            assertParamExists('cancelBulkOperation', 'operationId', operationId)
            const localVarPath = `/campaigns/bulk/operations/{operationId}/cancel`
                .replace(`{${"operationId"}}`, encodeURIComponent(String(operationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get detailed status of a specific bulk operation including progress and results
         * @summary Get bulk operation status by ID
         * @param {string} operationId Bulk operation ID
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBulkOperationStatus: async (operationId: string, body?: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'operationId' is not null or undefined
            assertParamExists('getBulkOperationStatus', 'operationId', operationId)
            const localVarPath = `/campaigns/bulk/operations/{operationId}/status`
                .replace(`{${"operationId"}}`, encodeURIComponent(String(operationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get current status and utilization of allocated bulk resources
         * @summary Get bulk resource allocation status
         * @param {string} allocationId Resource allocation ID
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBulkResourceStatus: async (allocationId: string, body?: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'allocationId' is not null or undefined
            assertParamExists('getBulkResourceStatus', 'allocationId', allocationId)
            const localVarPath = `/campaigns/bulk/resources/status/{allocationId}`
                .replace(`{${"allocationId"}}`, encodeURIComponent(String(allocationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a list of bulk operations with optional filtering by status, type, and time range
         * @summary List bulk operations with filtering
         * @param {ListBulkOperationsStatusEnum} [status] Filter by operation status
         * @param {ListBulkOperationsTypeEnum} [type] Filter by operation type
         * @param {number} [limit] Number of operations to return (max 1000)
         * @param {number} [offset] Number of operations to skip
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBulkOperations: async (status?: ListBulkOperationsStatusEnum, type?: ListBulkOperationsTypeEnum, limit?: number, offset?: number, body?: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/campaigns/bulk/operations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BulkOperationsApi - functional programming interface
 * @export
 */
export const BulkOperationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BulkOperationsApiAxiosParamCreator(configuration)
    return {
        /**
         * Allocate compute, network, and storage resources for bulk campaign operations with priority scheduling
         * @summary Allocate bulk resources for enterprise operations
         * @param {ModelsBulkResourceRequest} modelsBulkResourceRequest Bulk resource allocation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async allocateBulkResources(modelsBulkResourceRequest: ModelsBulkResourceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkValidateDNS200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.allocateBulkResources(modelsBulkResourceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkOperationsApi.allocateBulkResources']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Perform comprehensive analytics across multiple campaigns with advanced metrics and aggregation
         * @summary Analyze domains in bulk with enterprise intelligence
         * @param {ModelsBulkAnalyticsRequest} modelsBulkAnalyticsRequest Bulk analytics request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkAnalyzeDomains(modelsBulkAnalyticsRequest: ModelsBulkAnalyticsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkValidateDNS200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkAnalyzeDomains(modelsBulkAnalyticsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkOperationsApi.bulkAnalyzeDomains']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Generate large batches of domains with stealth-aware configuration and resource management
         * @summary Generate domains in bulk using orchestrator
         * @param {ModelsBulkDomainGenerationRequest} modelsBulkDomainGenerationRequest Bulk domain generation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkGenerateDomains(modelsBulkDomainGenerationRequest: ModelsBulkDomainGenerationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkValidateDNS200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkGenerateDomains(modelsBulkDomainGenerationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkOperationsApi.bulkGenerateDomains']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Perform bulk DNS validation with stealth detection avoidance and resource optimization
         * @summary Validate domains using bulk DNS validation with stealth
         * @param {ModelsBulkDNSValidationRequest} modelsBulkDNSValidationRequest Bulk DNS validation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkValidateDNS(modelsBulkDNSValidationRequest: ModelsBulkDNSValidationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkValidateDNS200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkValidateDNS(modelsBulkDNSValidationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkOperationsApi.bulkValidateDNS']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Perform bulk HTTP validation with keyword extraction, stealth detection avoidance, and resource optimization
         * @summary Validate domains using bulk HTTP validation with stealth
         * @param {ModelsBulkHTTPValidationRequest} modelsBulkHTTPValidationRequest Bulk HTTP validation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkValidateHTTP(modelsBulkHTTPValidationRequest: ModelsBulkHTTPValidationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkValidateDNS200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkValidateHTTP(modelsBulkHTTPValidationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkOperationsApi.bulkValidateHTTP']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Cancel running bulk operations and release allocated resources
         * @summary Cancel bulk operations
         * @param {string} operationId Bulk operation ID to cancel
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelBulkOperation(operationId: string, body?: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiOperationCancellationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelBulkOperation(operationId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkOperationsApi.cancelBulkOperation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get detailed status of a specific bulk operation including progress and results
         * @summary Get bulk operation status by ID
         * @param {string} operationId Bulk operation ID
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBulkOperationStatus(operationId: string, body?: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsBulkOperationStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBulkOperationStatus(operationId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkOperationsApi.getBulkOperationStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get current status and utilization of allocated bulk resources
         * @summary Get bulk resource allocation status
         * @param {string} allocationId Resource allocation ID
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBulkResourceStatus(allocationId: string, body?: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiBulkResourceStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBulkResourceStatus(allocationId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkOperationsApi.getBulkResourceStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a list of bulk operations with optional filtering by status, type, and time range
         * @summary List bulk operations with filtering
         * @param {ListBulkOperationsStatusEnum} [status] Filter by operation status
         * @param {ListBulkOperationsTypeEnum} [type] Filter by operation type
         * @param {number} [limit] Number of operations to return (max 1000)
         * @param {number} [offset] Number of operations to skip
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBulkOperations(status?: ListBulkOperationsStatusEnum, type?: ListBulkOperationsTypeEnum, limit?: number, offset?: number, body?: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkValidateDNS200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBulkOperations(status, type, limit, offset, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkOperationsApi.listBulkOperations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BulkOperationsApi - factory interface
 * @export
 */
export const BulkOperationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BulkOperationsApiFp(configuration)
    return {
        /**
         * Allocate compute, network, and storage resources for bulk campaign operations with priority scheduling
         * @summary Allocate bulk resources for enterprise operations
         * @param {ModelsBulkResourceRequest} modelsBulkResourceRequest Bulk resource allocation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        allocateBulkResources(modelsBulkResourceRequest: ModelsBulkResourceRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response> {
            return localVarFp.allocateBulkResources(modelsBulkResourceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Perform comprehensive analytics across multiple campaigns with advanced metrics and aggregation
         * @summary Analyze domains in bulk with enterprise intelligence
         * @param {ModelsBulkAnalyticsRequest} modelsBulkAnalyticsRequest Bulk analytics request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkAnalyzeDomains(modelsBulkAnalyticsRequest: ModelsBulkAnalyticsRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response> {
            return localVarFp.bulkAnalyzeDomains(modelsBulkAnalyticsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Generate large batches of domains with stealth-aware configuration and resource management
         * @summary Generate domains in bulk using orchestrator
         * @param {ModelsBulkDomainGenerationRequest} modelsBulkDomainGenerationRequest Bulk domain generation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkGenerateDomains(modelsBulkDomainGenerationRequest: ModelsBulkDomainGenerationRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response> {
            return localVarFp.bulkGenerateDomains(modelsBulkDomainGenerationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Perform bulk DNS validation with stealth detection avoidance and resource optimization
         * @summary Validate domains using bulk DNS validation with stealth
         * @param {ModelsBulkDNSValidationRequest} modelsBulkDNSValidationRequest Bulk DNS validation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkValidateDNS(modelsBulkDNSValidationRequest: ModelsBulkDNSValidationRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response> {
            return localVarFp.bulkValidateDNS(modelsBulkDNSValidationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Perform bulk HTTP validation with keyword extraction, stealth detection avoidance, and resource optimization
         * @summary Validate domains using bulk HTTP validation with stealth
         * @param {ModelsBulkHTTPValidationRequest} modelsBulkHTTPValidationRequest Bulk HTTP validation request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkValidateHTTP(modelsBulkHTTPValidationRequest: ModelsBulkHTTPValidationRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response> {
            return localVarFp.bulkValidateHTTP(modelsBulkHTTPValidationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Cancel running bulk operations and release allocated resources
         * @summary Cancel bulk operations
         * @param {string} operationId Bulk operation ID to cancel
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelBulkOperation(operationId: string, body?: object, options?: RawAxiosRequestConfig): AxiosPromise<ApiOperationCancellationResponse> {
            return localVarFp.cancelBulkOperation(operationId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * Get detailed status of a specific bulk operation including progress and results
         * @summary Get bulk operation status by ID
         * @param {string} operationId Bulk operation ID
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBulkOperationStatus(operationId: string, body?: object, options?: RawAxiosRequestConfig): AxiosPromise<ModelsBulkOperationStatus> {
            return localVarFp.getBulkOperationStatus(operationId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * Get current status and utilization of allocated bulk resources
         * @summary Get bulk resource allocation status
         * @param {string} allocationId Resource allocation ID
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBulkResourceStatus(allocationId: string, body?: object, options?: RawAxiosRequestConfig): AxiosPromise<ApiBulkResourceStatusResponse> {
            return localVarFp.getBulkResourceStatus(allocationId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a list of bulk operations with optional filtering by status, type, and time range
         * @summary List bulk operations with filtering
         * @param {ListBulkOperationsStatusEnum} [status] Filter by operation status
         * @param {ListBulkOperationsTypeEnum} [type] Filter by operation type
         * @param {number} [limit] Number of operations to return (max 1000)
         * @param {number} [offset] Number of operations to skip
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBulkOperations(status?: ListBulkOperationsStatusEnum, type?: ListBulkOperationsTypeEnum, limit?: number, offset?: number, body?: object, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response> {
            return localVarFp.listBulkOperations(status, type, limit, offset, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BulkOperationsApi - interface
 * @export
 * @interface BulkOperationsApi
 */
export interface BulkOperationsApiInterface {
    /**
     * Allocate compute, network, and storage resources for bulk campaign operations with priority scheduling
     * @summary Allocate bulk resources for enterprise operations
     * @param {ModelsBulkResourceRequest} modelsBulkResourceRequest Bulk resource allocation request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApiInterface
     */
    allocateBulkResources(modelsBulkResourceRequest: ModelsBulkResourceRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response>;

    /**
     * Perform comprehensive analytics across multiple campaigns with advanced metrics and aggregation
     * @summary Analyze domains in bulk with enterprise intelligence
     * @param {ModelsBulkAnalyticsRequest} modelsBulkAnalyticsRequest Bulk analytics request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApiInterface
     */
    bulkAnalyzeDomains(modelsBulkAnalyticsRequest: ModelsBulkAnalyticsRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response>;

    /**
     * Generate large batches of domains with stealth-aware configuration and resource management
     * @summary Generate domains in bulk using orchestrator
     * @param {ModelsBulkDomainGenerationRequest} modelsBulkDomainGenerationRequest Bulk domain generation request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApiInterface
     */
    bulkGenerateDomains(modelsBulkDomainGenerationRequest: ModelsBulkDomainGenerationRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response>;

    /**
     * Perform bulk DNS validation with stealth detection avoidance and resource optimization
     * @summary Validate domains using bulk DNS validation with stealth
     * @param {ModelsBulkDNSValidationRequest} modelsBulkDNSValidationRequest Bulk DNS validation request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApiInterface
     */
    bulkValidateDNS(modelsBulkDNSValidationRequest: ModelsBulkDNSValidationRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response>;

    /**
     * Perform bulk HTTP validation with keyword extraction, stealth detection avoidance, and resource optimization
     * @summary Validate domains using bulk HTTP validation with stealth
     * @param {ModelsBulkHTTPValidationRequest} modelsBulkHTTPValidationRequest Bulk HTTP validation request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApiInterface
     */
    bulkValidateHTTP(modelsBulkHTTPValidationRequest: ModelsBulkHTTPValidationRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response>;

    /**
     * Cancel running bulk operations and release allocated resources
     * @summary Cancel bulk operations
     * @param {string} operationId Bulk operation ID to cancel
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApiInterface
     */
    cancelBulkOperation(operationId: string, body?: object, options?: RawAxiosRequestConfig): AxiosPromise<ApiOperationCancellationResponse>;

    /**
     * Get detailed status of a specific bulk operation including progress and results
     * @summary Get bulk operation status by ID
     * @param {string} operationId Bulk operation ID
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApiInterface
     */
    getBulkOperationStatus(operationId: string, body?: object, options?: RawAxiosRequestConfig): AxiosPromise<ModelsBulkOperationStatus>;

    /**
     * Get current status and utilization of allocated bulk resources
     * @summary Get bulk resource allocation status
     * @param {string} allocationId Resource allocation ID
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApiInterface
     */
    getBulkResourceStatus(allocationId: string, body?: object, options?: RawAxiosRequestConfig): AxiosPromise<ApiBulkResourceStatusResponse>;

    /**
     * Get a list of bulk operations with optional filtering by status, type, and time range
     * @summary List bulk operations with filtering
     * @param {ListBulkOperationsStatusEnum} [status] Filter by operation status
     * @param {ListBulkOperationsTypeEnum} [type] Filter by operation type
     * @param {number} [limit] Number of operations to return (max 1000)
     * @param {number} [offset] Number of operations to skip
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApiInterface
     */
    listBulkOperations(status?: ListBulkOperationsStatusEnum, type?: ListBulkOperationsTypeEnum, limit?: number, offset?: number, body?: object, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response>;

}

/**
 * BulkOperationsApi - object-oriented interface
 * @export
 * @class BulkOperationsApi
 * @extends {BaseAPI}
 */
export class BulkOperationsApi extends BaseAPI implements BulkOperationsApiInterface {
    /**
     * Allocate compute, network, and storage resources for bulk campaign operations with priority scheduling
     * @summary Allocate bulk resources for enterprise operations
     * @param {ModelsBulkResourceRequest} modelsBulkResourceRequest Bulk resource allocation request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApi
     */
    public allocateBulkResources(modelsBulkResourceRequest: ModelsBulkResourceRequest, options?: RawAxiosRequestConfig) {
        return BulkOperationsApiFp(this.configuration).allocateBulkResources(modelsBulkResourceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Perform comprehensive analytics across multiple campaigns with advanced metrics and aggregation
     * @summary Analyze domains in bulk with enterprise intelligence
     * @param {ModelsBulkAnalyticsRequest} modelsBulkAnalyticsRequest Bulk analytics request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApi
     */
    public bulkAnalyzeDomains(modelsBulkAnalyticsRequest: ModelsBulkAnalyticsRequest, options?: RawAxiosRequestConfig) {
        return BulkOperationsApiFp(this.configuration).bulkAnalyzeDomains(modelsBulkAnalyticsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Generate large batches of domains with stealth-aware configuration and resource management
     * @summary Generate domains in bulk using orchestrator
     * @param {ModelsBulkDomainGenerationRequest} modelsBulkDomainGenerationRequest Bulk domain generation request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApi
     */
    public bulkGenerateDomains(modelsBulkDomainGenerationRequest: ModelsBulkDomainGenerationRequest, options?: RawAxiosRequestConfig) {
        return BulkOperationsApiFp(this.configuration).bulkGenerateDomains(modelsBulkDomainGenerationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Perform bulk DNS validation with stealth detection avoidance and resource optimization
     * @summary Validate domains using bulk DNS validation with stealth
     * @param {ModelsBulkDNSValidationRequest} modelsBulkDNSValidationRequest Bulk DNS validation request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApi
     */
    public bulkValidateDNS(modelsBulkDNSValidationRequest: ModelsBulkDNSValidationRequest, options?: RawAxiosRequestConfig) {
        return BulkOperationsApiFp(this.configuration).bulkValidateDNS(modelsBulkDNSValidationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Perform bulk HTTP validation with keyword extraction, stealth detection avoidance, and resource optimization
     * @summary Validate domains using bulk HTTP validation with stealth
     * @param {ModelsBulkHTTPValidationRequest} modelsBulkHTTPValidationRequest Bulk HTTP validation request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApi
     */
    public bulkValidateHTTP(modelsBulkHTTPValidationRequest: ModelsBulkHTTPValidationRequest, options?: RawAxiosRequestConfig) {
        return BulkOperationsApiFp(this.configuration).bulkValidateHTTP(modelsBulkHTTPValidationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Cancel running bulk operations and release allocated resources
     * @summary Cancel bulk operations
     * @param {string} operationId Bulk operation ID to cancel
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApi
     */
    public cancelBulkOperation(operationId: string, body?: object, options?: RawAxiosRequestConfig) {
        return BulkOperationsApiFp(this.configuration).cancelBulkOperation(operationId, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get detailed status of a specific bulk operation including progress and results
     * @summary Get bulk operation status by ID
     * @param {string} operationId Bulk operation ID
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApi
     */
    public getBulkOperationStatus(operationId: string, body?: object, options?: RawAxiosRequestConfig) {
        return BulkOperationsApiFp(this.configuration).getBulkOperationStatus(operationId, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get current status and utilization of allocated bulk resources
     * @summary Get bulk resource allocation status
     * @param {string} allocationId Resource allocation ID
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApi
     */
    public getBulkResourceStatus(allocationId: string, body?: object, options?: RawAxiosRequestConfig) {
        return BulkOperationsApiFp(this.configuration).getBulkResourceStatus(allocationId, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a list of bulk operations with optional filtering by status, type, and time range
     * @summary List bulk operations with filtering
     * @param {ListBulkOperationsStatusEnum} [status] Filter by operation status
     * @param {ListBulkOperationsTypeEnum} [type] Filter by operation type
     * @param {number} [limit] Number of operations to return (max 1000)
     * @param {number} [offset] Number of operations to skip
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkOperationsApi
     */
    public listBulkOperations(status?: ListBulkOperationsStatusEnum, type?: ListBulkOperationsTypeEnum, limit?: number, offset?: number, body?: object, options?: RawAxiosRequestConfig) {
        return BulkOperationsApiFp(this.configuration).listBulkOperations(status, type, limit, offset, body, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
  * @export
  * @enum {string}
  */
export enum ListBulkOperationsStatusEnum {
    queued = 'queued',
    running = 'running',
    completed = 'completed',
    failed = 'failed',
    cancelled = 'cancelled'
}
/**
  * @export
  * @enum {string}
  */
export enum ListBulkOperationsTypeEnum {
    domain_generation = 'domain_generation',
    dns_validation = 'dns_validation',
    http_validation = 'http_validation',
    analytics = 'analytics'
}
