/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * A comprehensive API for domain generation, validation, and management operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiAPIResponse } from '../models';
// @ts-ignore
import type { ApiBulkDatabaseQueryRequest } from '../models';
// @ts-ignore
import type { ApiBulkDatabaseStatsRequest } from '../models';
// @ts-ignore
import type { BulkValidateDNS200Response } from '../models';
/**
 * DatabaseApi - axios parameter creator
 * @export
 */
export const DatabaseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Execute multiple SQL queries against the database with security restrictions for enterprise operations
         * @summary Execute bulk database queries
         * @param {string} xRequestedWith Must be XMLHttpRequest
         * @param {ApiBulkDatabaseQueryRequest} apiBulkDatabaseQueryRequest Bulk query request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2DatabaseQueryPost: async (xRequestedWith: string, apiBulkDatabaseQueryRequest: ApiBulkDatabaseQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xRequestedWith' is not null or undefined
            assertParamExists('apiV2DatabaseQueryPost', 'xRequestedWith', xRequestedWith)
            // verify required parameter 'apiBulkDatabaseQueryRequest' is not null or undefined
            assertParamExists('apiV2DatabaseQueryPost', 'apiBulkDatabaseQueryRequest', apiBulkDatabaseQueryRequest)
            const localVarPath = `/api/v2/database/query`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xRequestedWith != null) {
                localVarHeaderParameter['X-Requested-With'] = String(xRequestedWith);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiBulkDatabaseQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve comprehensive database statistics including schema and table-level details for enterprise monitoring
         * @summary Get bulk database statistics
         * @param {string} xRequestedWith Must be XMLHttpRequest
         * @param {ApiBulkDatabaseStatsRequest} apiBulkDatabaseStatsRequest Bulk stats request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2DatabaseStatsPost: async (xRequestedWith: string, apiBulkDatabaseStatsRequest: ApiBulkDatabaseStatsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xRequestedWith' is not null or undefined
            assertParamExists('apiV2DatabaseStatsPost', 'xRequestedWith', xRequestedWith)
            // verify required parameter 'apiBulkDatabaseStatsRequest' is not null or undefined
            assertParamExists('apiV2DatabaseStatsPost', 'apiBulkDatabaseStatsRequest', apiBulkDatabaseStatsRequest)
            const localVarPath = `/api/v2/database/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xRequestedWith != null) {
                localVarHeaderParameter['X-Requested-With'] = String(xRequestedWith);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiBulkDatabaseStatsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DatabaseApi - functional programming interface
 * @export
 */
export const DatabaseApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DatabaseApiAxiosParamCreator(configuration)
    return {
        /**
         * Execute multiple SQL queries against the database with security restrictions for enterprise operations
         * @summary Execute bulk database queries
         * @param {string} xRequestedWith Must be XMLHttpRequest
         * @param {ApiBulkDatabaseQueryRequest} apiBulkDatabaseQueryRequest Bulk query request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV2DatabaseQueryPost(xRequestedWith: string, apiBulkDatabaseQueryRequest: ApiBulkDatabaseQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkValidateDNS200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV2DatabaseQueryPost(xRequestedWith, apiBulkDatabaseQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DatabaseApi.apiV2DatabaseQueryPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve comprehensive database statistics including schema and table-level details for enterprise monitoring
         * @summary Get bulk database statistics
         * @param {string} xRequestedWith Must be XMLHttpRequest
         * @param {ApiBulkDatabaseStatsRequest} apiBulkDatabaseStatsRequest Bulk stats request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV2DatabaseStatsPost(xRequestedWith: string, apiBulkDatabaseStatsRequest: ApiBulkDatabaseStatsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkValidateDNS200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV2DatabaseStatsPost(xRequestedWith, apiBulkDatabaseStatsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DatabaseApi.apiV2DatabaseStatsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DatabaseApi - factory interface
 * @export
 */
export const DatabaseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DatabaseApiFp(configuration)
    return {
        /**
         * Execute multiple SQL queries against the database with security restrictions for enterprise operations
         * @summary Execute bulk database queries
         * @param {string} xRequestedWith Must be XMLHttpRequest
         * @param {ApiBulkDatabaseQueryRequest} apiBulkDatabaseQueryRequest Bulk query request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2DatabaseQueryPost(xRequestedWith: string, apiBulkDatabaseQueryRequest: ApiBulkDatabaseQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response> {
            return localVarFp.apiV2DatabaseQueryPost(xRequestedWith, apiBulkDatabaseQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve comprehensive database statistics including schema and table-level details for enterprise monitoring
         * @summary Get bulk database statistics
         * @param {string} xRequestedWith Must be XMLHttpRequest
         * @param {ApiBulkDatabaseStatsRequest} apiBulkDatabaseStatsRequest Bulk stats request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2DatabaseStatsPost(xRequestedWith: string, apiBulkDatabaseStatsRequest: ApiBulkDatabaseStatsRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response> {
            return localVarFp.apiV2DatabaseStatsPost(xRequestedWith, apiBulkDatabaseStatsRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DatabaseApi - interface
 * @export
 * @interface DatabaseApi
 */
export interface DatabaseApiInterface {
    /**
     * Execute multiple SQL queries against the database with security restrictions for enterprise operations
     * @summary Execute bulk database queries
     * @param {string} xRequestedWith Must be XMLHttpRequest
     * @param {ApiBulkDatabaseQueryRequest} apiBulkDatabaseQueryRequest Bulk query request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatabaseApiInterface
     */
    apiV2DatabaseQueryPost(xRequestedWith: string, apiBulkDatabaseQueryRequest: ApiBulkDatabaseQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response>;

    /**
     * Retrieve comprehensive database statistics including schema and table-level details for enterprise monitoring
     * @summary Get bulk database statistics
     * @param {string} xRequestedWith Must be XMLHttpRequest
     * @param {ApiBulkDatabaseStatsRequest} apiBulkDatabaseStatsRequest Bulk stats request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatabaseApiInterface
     */
    apiV2DatabaseStatsPost(xRequestedWith: string, apiBulkDatabaseStatsRequest: ApiBulkDatabaseStatsRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkValidateDNS200Response>;

}

/**
 * DatabaseApi - object-oriented interface
 * @export
 * @class DatabaseApi
 * @extends {BaseAPI}
 */
export class DatabaseApi extends BaseAPI implements DatabaseApiInterface {
    /**
     * Execute multiple SQL queries against the database with security restrictions for enterprise operations
     * @summary Execute bulk database queries
     * @param {string} xRequestedWith Must be XMLHttpRequest
     * @param {ApiBulkDatabaseQueryRequest} apiBulkDatabaseQueryRequest Bulk query request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatabaseApi
     */
    public apiV2DatabaseQueryPost(xRequestedWith: string, apiBulkDatabaseQueryRequest: ApiBulkDatabaseQueryRequest, options?: RawAxiosRequestConfig) {
        return DatabaseApiFp(this.configuration).apiV2DatabaseQueryPost(xRequestedWith, apiBulkDatabaseQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve comprehensive database statistics including schema and table-level details for enterprise monitoring
     * @summary Get bulk database statistics
     * @param {string} xRequestedWith Must be XMLHttpRequest
     * @param {ApiBulkDatabaseStatsRequest} apiBulkDatabaseStatsRequest Bulk stats request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatabaseApi
     */
    public apiV2DatabaseStatsPost(xRequestedWith: string, apiBulkDatabaseStatsRequest: ApiBulkDatabaseStatsRequest, options?: RawAxiosRequestConfig) {
        return DatabaseApiFp(this.configuration).apiV2DatabaseStatsPost(xRequestedWith, apiBulkDatabaseStatsRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

