/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorEnvelope } from '../models';
// @ts-ignore
import type { KeywordRuleDTO } from '../models';
// @ts-ignore
import type { KeywordRuleType } from '../models';
/**
 * KeywordRulesApi - axios parameter creator
 * @export
 */
export const KeywordRulesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Query keyword rules
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [keywordSetId] 
         * @param {KeywordRuleType} [ruleType] 
         * @param {string} [category] 
         * @param {boolean} [isCaseSensitive] 
         * @param {string} [pattern] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        keywordRulesQuery: async (limit?: number, offset?: number, keywordSetId?: string, ruleType?: KeywordRuleType, category?: string, isCaseSensitive?: boolean, pattern?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/keyword-rules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (keywordSetId !== undefined) {
                localVarQueryParameter['keyword_set_id'] = keywordSetId;
            }

            if (ruleType !== undefined) {
                localVarQueryParameter['rule_type'] = ruleType;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (isCaseSensitive !== undefined) {
                localVarQueryParameter['is_case_sensitive'] = isCaseSensitive;
            }

            if (pattern !== undefined) {
                localVarQueryParameter['pattern'] = pattern;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * KeywordRulesApi - functional programming interface
 * @export
 */
export const KeywordRulesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = KeywordRulesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Query keyword rules
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [keywordSetId] 
         * @param {KeywordRuleType} [ruleType] 
         * @param {string} [category] 
         * @param {boolean} [isCaseSensitive] 
         * @param {string} [pattern] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async keywordRulesQuery(limit?: number, offset?: number, keywordSetId?: string, ruleType?: KeywordRuleType, category?: string, isCaseSensitive?: boolean, pattern?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<KeywordRuleDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.keywordRulesQuery(limit, offset, keywordSetId, ruleType, category, isCaseSensitive, pattern, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KeywordRulesApi.keywordRulesQuery']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * KeywordRulesApi - factory interface
 * @export
 */
export const KeywordRulesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = KeywordRulesApiFp(configuration)
    return {
        /**
         * 
         * @summary Query keyword rules
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [keywordSetId] 
         * @param {KeywordRuleType} [ruleType] 
         * @param {string} [category] 
         * @param {boolean} [isCaseSensitive] 
         * @param {string} [pattern] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        keywordRulesQuery(limit?: number, offset?: number, keywordSetId?: string, ruleType?: KeywordRuleType, category?: string, isCaseSensitive?: boolean, pattern?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<KeywordRuleDTO>> {
            return localVarFp.keywordRulesQuery(limit, offset, keywordSetId, ruleType, category, isCaseSensitive, pattern, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * KeywordRulesApi - interface
 * @export
 * @interface KeywordRulesApi
 */
export interface KeywordRulesApiInterface {
    /**
     * 
     * @summary Query keyword rules
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {string} [keywordSetId] 
     * @param {KeywordRuleType} [ruleType] 
     * @param {string} [category] 
     * @param {boolean} [isCaseSensitive] 
     * @param {string} [pattern] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordRulesApiInterface
     */
    keywordRulesQuery(limit?: number, offset?: number, keywordSetId?: string, ruleType?: KeywordRuleType, category?: string, isCaseSensitive?: boolean, pattern?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<KeywordRuleDTO>>;

}

/**
 * KeywordRulesApi - object-oriented interface
 * @export
 * @class KeywordRulesApi
 * @extends {BaseAPI}
 */
export class KeywordRulesApi extends BaseAPI implements KeywordRulesApiInterface {
    /**
     * 
     * @summary Query keyword rules
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {string} [keywordSetId] 
     * @param {KeywordRuleType} [ruleType] 
     * @param {string} [category] 
     * @param {boolean} [isCaseSensitive] 
     * @param {string} [pattern] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeywordRulesApi
     */
    public keywordRulesQuery(limit?: number, offset?: number, keywordSetId?: string, ruleType?: KeywordRuleType, category?: string, isCaseSensitive?: boolean, pattern?: string, options?: RawAxiosRequestConfig) {
        return KeywordRulesApiFp(this.configuration).keywordRulesQuery(limit, offset, keywordSetId, ruleType, category, isCaseSensitive, pattern, options).then((request) => request(this.axios, this.basePath));
    }
}

