/* tslint:disable */
/* eslint-disable */
/**
 * Studio API
 * Studio API for managing campaigns, personas, proxies, and keyword sets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { GetCampaignDetails200Response } from '../models';
/**
 * PauseApi - axios parameter creator
 * @export
 */
export const PauseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Post pause endpoint
         * @summary Pause campaign
         * @param {string} campaignId CampaignId UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pauseCampaign: async (campaignId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'campaignId' is not null or undefined
            assertParamExists('pauseCampaign', 'campaignId', campaignId)
            const localVarPath = `/{campaignId}/pause`
                .replace(`{${"campaignId"}}`, encodeURIComponent(String(campaignId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PauseApi - functional programming interface
 * @export
 */
export const PauseApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PauseApiAxiosParamCreator(configuration)
    return {
        /**
         * Post pause endpoint
         * @summary Pause campaign
         * @param {string} campaignId CampaignId UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pauseCampaign(campaignId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetCampaignDetails200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pauseCampaign(campaignId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PauseApi.pauseCampaign']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PauseApi - factory interface
 * @export
 */
export const PauseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PauseApiFp(configuration)
    return {
        /**
         * Post pause endpoint
         * @summary Pause campaign
         * @param {string} campaignId CampaignId UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pauseCampaign(campaignId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetCampaignDetails200Response> {
            return localVarFp.pauseCampaign(campaignId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PauseApi - interface
 * @export
 * @interface PauseApi
 */
export interface PauseApiInterface {
    /**
     * Post pause endpoint
     * @summary Pause campaign
     * @param {string} campaignId CampaignId UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PauseApiInterface
     */
    pauseCampaign(campaignId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetCampaignDetails200Response>;

}

/**
 * PauseApi - object-oriented interface
 * @export
 * @class PauseApi
 * @extends {BaseAPI}
 */
export class PauseApi extends BaseAPI implements PauseApiInterface {
    /**
     * Post pause endpoint
     * @summary Pause campaign
     * @param {string} campaignId CampaignId UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PauseApi
     */
    public pauseCampaign(campaignId: string, options?: RawAxiosRequestConfig) {
        return PauseApiFp(this.configuration).pauseCampaign(campaignId, options).then((request) => request(this.axios, this.basePath));
    }
}

