/* tslint:disable */
/* eslint-disable */
/**
 * Domain Flow API
 * DomainFlow is a campaign-focused domain intelligence platform. The API manages personas, proxies, keyword pipelines, monitoring, and campaign execution while exposing configuration and scoring surfaces for both UI and automation clients. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@domainflow.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreatePersonaRequest } from '../models';
// @ts-ignore
import type { ErrorEnvelope } from '../models';
// @ts-ignore
import type { PersonaResponse } from '../models';
// @ts-ignore
import type { PersonaTestResponse } from '../models';
// @ts-ignore
import type { PersonaType } from '../models';
// @ts-ignore
import type { UpdatePersonaRequest } from '../models';
/**
 * PersonasApi - axios parameter creator
 * @export
 */
export const PersonasApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create persona
         * @param {CreatePersonaRequest} createPersonaRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasCreate: async (createPersonaRequest: CreatePersonaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createPersonaRequest' is not null or undefined
            assertParamExists('personasCreate', 'createPersonaRequest', createPersonaRequest)
            const localVarPath = `/personas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPersonaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete persona
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('personasDelete', 'id', id)
            const localVarPath = `/personas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get persona by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('personasGet', 'id', id)
            const localVarPath = `/personas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get DNS persona by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasGetDns: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('personasGetDns', 'id', id)
            const localVarPath = `/personas/dns/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get HTTP persona by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasGetHttp: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('personasGetHttp', 'id', id)
            const localVarPath = `/personas/http/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List personas
         * @param {number} [limit] Page size (items per page)
         * @param {number} [offset] Zero-based offset
         * @param {boolean} [isEnabled] Filter by enabled state
         * @param {PersonaType} [personaType] Filter by persona type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasList: async (limit?: number, offset?: number, isEnabled?: boolean, personaType?: PersonaType, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/personas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (isEnabled !== undefined) {
                localVarQueryParameter['isEnabled'] = isEnabled;
            }

            if (personaType !== undefined) {
                localVarQueryParameter['personaType'] = personaType;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Test persona
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasTest: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('personasTest', 'id', id)
            const localVarPath = `/personas/{id}/test`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update persona
         * @param {string} id 
         * @param {UpdatePersonaRequest} updatePersonaRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasUpdate: async (id: string, updatePersonaRequest: UpdatePersonaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('personasUpdate', 'id', id)
            // verify required parameter 'updatePersonaRequest' is not null or undefined
            assertParamExists('personasUpdate', 'updatePersonaRequest', updatePersonaRequest)
            const localVarPath = `/personas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePersonaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PersonasApi - functional programming interface
 * @export
 */
export const PersonasApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PersonasApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create persona
         * @param {CreatePersonaRequest} createPersonaRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async personasCreate(createPersonaRequest: CreatePersonaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonaResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.personasCreate(createPersonaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonasApi.personasCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete persona
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async personasDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.personasDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonasApi.personasDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get persona by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async personasGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonaResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.personasGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonasApi.personasGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get DNS persona by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async personasGetDns(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonaResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.personasGetDns(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonasApi.personasGetDns']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get HTTP persona by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async personasGetHttp(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonaResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.personasGetHttp(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonasApi.personasGetHttp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List personas
         * @param {number} [limit] Page size (items per page)
         * @param {number} [offset] Zero-based offset
         * @param {boolean} [isEnabled] Filter by enabled state
         * @param {PersonaType} [personaType] Filter by persona type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async personasList(limit?: number, offset?: number, isEnabled?: boolean, personaType?: PersonaType, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PersonaResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.personasList(limit, offset, isEnabled, personaType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonasApi.personasList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Test persona
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async personasTest(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonaTestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.personasTest(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonasApi.personasTest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update persona
         * @param {string} id 
         * @param {UpdatePersonaRequest} updatePersonaRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async personasUpdate(id: string, updatePersonaRequest: UpdatePersonaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonaResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.personasUpdate(id, updatePersonaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonasApi.personasUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PersonasApi - factory interface
 * @export
 */
export const PersonasApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PersonasApiFp(configuration)
    return {
        /**
         * 
         * @summary Create persona
         * @param {CreatePersonaRequest} createPersonaRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasCreate(createPersonaRequest: CreatePersonaRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonaResponse> {
            return localVarFp.personasCreate(createPersonaRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete persona
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.personasDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get persona by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<PersonaResponse> {
            return localVarFp.personasGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get DNS persona by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasGetDns(id: string, options?: RawAxiosRequestConfig): AxiosPromise<PersonaResponse> {
            return localVarFp.personasGetDns(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get HTTP persona by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasGetHttp(id: string, options?: RawAxiosRequestConfig): AxiosPromise<PersonaResponse> {
            return localVarFp.personasGetHttp(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List personas
         * @param {number} [limit] Page size (items per page)
         * @param {number} [offset] Zero-based offset
         * @param {boolean} [isEnabled] Filter by enabled state
         * @param {PersonaType} [personaType] Filter by persona type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasList(limit?: number, offset?: number, isEnabled?: boolean, personaType?: PersonaType, options?: RawAxiosRequestConfig): AxiosPromise<Array<PersonaResponse>> {
            return localVarFp.personasList(limit, offset, isEnabled, personaType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Test persona
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasTest(id: string, options?: RawAxiosRequestConfig): AxiosPromise<PersonaTestResponse> {
            return localVarFp.personasTest(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update persona
         * @param {string} id 
         * @param {UpdatePersonaRequest} updatePersonaRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personasUpdate(id: string, updatePersonaRequest: UpdatePersonaRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonaResponse> {
            return localVarFp.personasUpdate(id, updatePersonaRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PersonasApi - interface
 * @export
 * @interface PersonasApi
 */
export interface PersonasApiInterface {
    /**
     * 
     * @summary Create persona
     * @param {CreatePersonaRequest} createPersonaRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApiInterface
     */
    personasCreate(createPersonaRequest: CreatePersonaRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonaResponse>;

    /**
     * 
     * @summary Delete persona
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApiInterface
     */
    personasDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get persona by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApiInterface
     */
    personasGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<PersonaResponse>;

    /**
     * 
     * @summary Get DNS persona by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApiInterface
     */
    personasGetDns(id: string, options?: RawAxiosRequestConfig): AxiosPromise<PersonaResponse>;

    /**
     * 
     * @summary Get HTTP persona by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApiInterface
     */
    personasGetHttp(id: string, options?: RawAxiosRequestConfig): AxiosPromise<PersonaResponse>;

    /**
     * 
     * @summary List personas
     * @param {number} [limit] Page size (items per page)
     * @param {number} [offset] Zero-based offset
     * @param {boolean} [isEnabled] Filter by enabled state
     * @param {PersonaType} [personaType] Filter by persona type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApiInterface
     */
    personasList(limit?: number, offset?: number, isEnabled?: boolean, personaType?: PersonaType, options?: RawAxiosRequestConfig): AxiosPromise<Array<PersonaResponse>>;

    /**
     * 
     * @summary Test persona
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApiInterface
     */
    personasTest(id: string, options?: RawAxiosRequestConfig): AxiosPromise<PersonaTestResponse>;

    /**
     * 
     * @summary Update persona
     * @param {string} id 
     * @param {UpdatePersonaRequest} updatePersonaRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApiInterface
     */
    personasUpdate(id: string, updatePersonaRequest: UpdatePersonaRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonaResponse>;

}

/**
 * PersonasApi - object-oriented interface
 * @export
 * @class PersonasApi
 * @extends {BaseAPI}
 */
export class PersonasApi extends BaseAPI implements PersonasApiInterface {
    /**
     * 
     * @summary Create persona
     * @param {CreatePersonaRequest} createPersonaRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApi
     */
    public personasCreate(createPersonaRequest: CreatePersonaRequest, options?: RawAxiosRequestConfig) {
        return PersonasApiFp(this.configuration).personasCreate(createPersonaRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete persona
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApi
     */
    public personasDelete(id: string, options?: RawAxiosRequestConfig) {
        return PersonasApiFp(this.configuration).personasDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get persona by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApi
     */
    public personasGet(id: string, options?: RawAxiosRequestConfig) {
        return PersonasApiFp(this.configuration).personasGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get DNS persona by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApi
     */
    public personasGetDns(id: string, options?: RawAxiosRequestConfig) {
        return PersonasApiFp(this.configuration).personasGetDns(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get HTTP persona by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApi
     */
    public personasGetHttp(id: string, options?: RawAxiosRequestConfig) {
        return PersonasApiFp(this.configuration).personasGetHttp(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List personas
     * @param {number} [limit] Page size (items per page)
     * @param {number} [offset] Zero-based offset
     * @param {boolean} [isEnabled] Filter by enabled state
     * @param {PersonaType} [personaType] Filter by persona type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApi
     */
    public personasList(limit?: number, offset?: number, isEnabled?: boolean, personaType?: PersonaType, options?: RawAxiosRequestConfig) {
        return PersonasApiFp(this.configuration).personasList(limit, offset, isEnabled, personaType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Test persona
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApi
     */
    public personasTest(id: string, options?: RawAxiosRequestConfig) {
        return PersonasApiFp(this.configuration).personasTest(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update persona
     * @param {string} id 
     * @param {UpdatePersonaRequest} updatePersonaRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonasApi
     */
    public personasUpdate(id: string, updatePersonaRequest: UpdatePersonaRequest, options?: RawAxiosRequestConfig) {
        return PersonasApiFp(this.configuration).personasUpdate(id, updatePersonaRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

