-- Rollback Performance Monitoring Schema

-- Drop indexes
DROP INDEX IF EXISTS idx_query_performance_metrics_query_hash;
DROP INDEX IF EXISTS idx_query_performance_metrics_query_type;
DROP INDEX IF EXISTS idx_query_performance_metrics_executed_at;
DROP INDEX IF EXISTS idx_query_performance_metrics_execution_time;
DROP INDEX IF EXISTS idx_query_performance_metrics_service_name;
DROP INDEX IF EXISTS idx_query_performance_metrics_campaign_id;
DROP INDEX IF EXISTS idx_query_performance_metrics_campaign_phase;
DROP INDEX IF EXISTS idx_query_performance_metrics_performance_category;
DROP INDEX IF EXISTS idx_query_performance_metrics_needs_optimization;
DROP INDEX IF EXISTS idx_query_performance_metrics_user_id;
DROP INDEX IF EXISTS idx_query_performance_metrics_type_time;
DROP INDEX IF EXISTS idx_query_performance_metrics_service_time;
DROP INDEX IF EXISTS idx_query_performance_metrics_slow_queries;
DROP INDEX IF EXISTS idx_query_performance_metrics_table_names_gin;
DROP INDEX IF EXISTS idx_query_performance_metrics_index_usage_gin;
DROP INDEX IF EXISTS idx_query_performance_metrics_query_plan_gin;
DROP INDEX IF EXISTS idx_query_performance_metrics_optimization_suggestions_gin;

DROP INDEX IF EXISTS idx_resource_utilization_metrics_service_name;
DROP INDEX IF EXISTS idx_resource_utilization_metrics_resource_type;
DROP INDEX IF EXISTS idx_resource_utilization_metrics_recorded_at;
DROP INDEX IF EXISTS idx_resource_utilization_metrics_utilization_pct;
DROP INDEX IF EXISTS idx_resource_utilization_metrics_bottleneck_detected;
DROP INDEX IF EXISTS idx_resource_utilization_metrics_campaign_id;
DROP INDEX IF EXISTS idx_resource_utilization_metrics_campaign_phase;
DROP INDEX IF EXISTS idx_resource_utilization_metrics_component;
DROP INDEX IF EXISTS idx_resource_utilization_metrics_service_resource;
DROP INDEX IF EXISTS idx_resource_utilization_metrics_high_utilization;
DROP INDEX IF EXISTS idx_resource_utilization_metrics_optimization_gin;

DROP INDEX IF EXISTS idx_connection_pool_metrics_recorded_at;
DROP INDEX IF EXISTS idx_connection_pool_metrics_pool_utilization;
DROP INDEX IF EXISTS idx_connection_pool_metrics_service_name;
DROP INDEX IF EXISTS idx_connection_pool_metrics_database_name;
DROP INDEX IF EXISTS idx_connection_pool_metrics_connection_errors;
DROP INDEX IF EXISTS idx_connection_pool_metrics_wait_count;
DROP INDEX IF EXISTS idx_connection_pool_metrics_service_utilization;
DROP INDEX IF EXISTS idx_connection_pool_metrics_high_utilization;

DROP INDEX IF EXISTS idx_pagination_performance_metrics_table_name;
DROP INDEX IF EXISTS idx_pagination_performance_metrics_pagination_type;
DROP INDEX IF EXISTS idx_pagination_performance_metrics_recorded_at;
DROP INDEX IF EXISTS idx_pagination_performance_metrics_execution_time;
DROP INDEX IF EXISTS idx_pagination_performance_metrics_page_size;
DROP INDEX IF EXISTS idx_pagination_performance_metrics_service_name;
DROP INDEX IF EXISTS idx_pagination_performance_metrics_campaign_id;
DROP INDEX IF EXISTS idx_pagination_performance_metrics_user_id;
DROP INDEX IF EXISTS idx_pagination_performance_metrics_table_type;
DROP INDEX IF EXISTS idx_pagination_performance_metrics_slow_pagination;
DROP INDEX IF EXISTS idx_pagination_performance_metrics_large_pages;

-- Drop tables
DROP TABLE IF EXISTS pagination_performance_metrics;
DROP TABLE IF EXISTS connection_pool_metrics;
DROP TABLE IF EXISTS resource_utilization_metrics;
DROP TABLE IF EXISTS query_performance_metrics;